// AUTO-GENERATED by zirgen EDSL WGSL spike. Do not edit.
fn recursion(code0: u32, out1: u32, data2: u32, mix3: u32, accum4: u32) -> Val {
if ((load_at(1u, code0, 0u)) != 0u) {
// components/plonk.h:202
let x5_tuple = extern_plonkRead();
let x5: Val = x5_tuple[0u];
let x6: Val = x5_tuple[1u];
let x7: Val = x5_tuple[2u];
let x8: Val = x5_tuple[3u];
let x9: Val = x5_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(50u, data2, x5);
// zirgen/circuit/recursion/wom.cpp:43
store_at(51u, data2, x6);
store_at(52u, data2, x7);
store_at(53u, data2, x8);
store_at(54u, data2, x9);
// components/plonk.h:202
let x10_tuple = extern_plonkRead();
let x10: Val = x10_tuple[0u];
let x11: Val = x10_tuple[1u];
let x12: Val = x10_tuple[2u];
let x13: Val = x10_tuple[3u];
let x14: Val = x10_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(55u, data2, x10);
// zirgen/circuit/recursion/wom.cpp:43
store_at(56u, data2, x11);
store_at(57u, data2, x12);
store_at(58u, data2, x13);
store_at(59u, data2, x14);
// components/plonk.h:202
let x15_tuple = extern_plonkRead();
let x15: Val = x15_tuple[0u];
let x16: Val = x15_tuple[1u];
let x17: Val = x15_tuple[2u];
let x18: Val = x15_tuple[3u];
let x19: Val = x15_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(60u, data2, x15);
// zirgen/circuit/recursion/wom.cpp:43
store_at(61u, data2, x16);
store_at(62u, data2, x17);
store_at(63u, data2, x18);
store_at(64u, data2, x19);
// components/plonk.h:202
let x20_tuple = extern_plonkRead();
let x20: Val = x20_tuple[0u];
let x21: Val = x20_tuple[1u];
let x22: Val = x20_tuple[2u];
let x23: Val = x20_tuple[3u];
let x24: Val = x20_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(65u, data2, x20);
// zirgen/circuit/recursion/wom.cpp:43
store_at(66u, data2, x21);
store_at(67u, data2, x22);
store_at(68u, data2, x23);
store_at(69u, data2, x24);
// components/plonk.h:202
let x25_tuple = extern_plonkRead();
let x25: Val = x25_tuple[0u];
let x26: Val = x25_tuple[1u];
let x27: Val = x25_tuple[2u];
let x28: Val = x25_tuple[3u];
let x29: Val = x25_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(70u, data2, x25);
// zirgen/circuit/recursion/wom.cpp:43
store_at(71u, data2, x26);
store_at(72u, data2, x27);
store_at(73u, data2, x28);
store_at(74u, data2, x29);
// components/plonk.h:202
let x30_tuple = extern_plonkRead();
let x30: Val = x30_tuple[0u];
let x31: Val = x30_tuple[1u];
let x32: Val = x30_tuple[2u];
let x33: Val = x30_tuple[3u];
let x34: Val = x30_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(75u, data2, x30);
// zirgen/circuit/recursion/wom.cpp:43
store_at(76u, data2, x31);
store_at(77u, data2, x32);
store_at(78u, data2, x33);
store_at(79u, data2, x34);
// components/plonk.h:202
let x35_tuple = extern_plonkRead();
let x35: Val = x35_tuple[0u];
let x36: Val = x35_tuple[1u];
let x37: Val = x35_tuple[2u];
let x38: Val = x35_tuple[3u];
let x39: Val = x35_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(80u, data2, x35);
// zirgen/circuit/recursion/wom.cpp:43
store_at(81u, data2, x36);
store_at(82u, data2, x37);
store_at(83u, data2, x38);
store_at(84u, data2, x39);
// components/plonk.h:202
let x40_tuple = extern_plonkRead();
let x40: Val = x40_tuple[0u];
let x41: Val = x40_tuple[1u];
let x42: Val = x40_tuple[2u];
let x43: Val = x40_tuple[3u];
let x44: Val = x40_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(85u, data2, x40);
// zirgen/circuit/recursion/wom.cpp:43
store_at(86u, data2, x41);
store_at(87u, data2, x42);
store_at(88u, data2, x43);
store_at(89u, data2, x44);
// components/plonk.h:202
let x45_tuple = extern_plonkRead();
let x45: Val = x45_tuple[0u];
let x46: Val = x45_tuple[1u];
let x47: Val = x45_tuple[2u];
let x48: Val = x45_tuple[3u];
let x49: Val = x45_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(0u, data2, x45);
// zirgen/circuit/recursion/wom.cpp:43
store_at(1u, data2, x46);
store_at(2u, data2, x47);
store_at(3u, data2, x48);
store_at(4u, data2, x49);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x50: Val = load_at(50u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x51: Val = sub(x50, load_at(0u, data2, 1u));
// zirgen/circuit/recursion/wom.cpp:74
let x52: Val = sub(268435454u, x51);
eqz(mul(x51, x52));
if ((x52) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(1u, data2, 1u), load_at(51u, data2, 0u)));
eqz(sub(load_at(2u, data2, 1u), load_at(52u, data2, 0u)));
eqz(sub(load_at(3u, data2, 1u), load_at(53u, data2, 0u)));
eqz(sub(load_at(4u, data2, 1u), load_at(54u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x53: Val = load_at(55u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x54: Val = sub(x53, x50);
// zirgen/circuit/recursion/wom.cpp:74
let x55: Val = sub(268435454u, x54);
eqz(mul(x54, x55));
if ((x55) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(51u, data2, 0u), load_at(56u, data2, 0u)));
eqz(sub(load_at(52u, data2, 0u), load_at(57u, data2, 0u)));
eqz(sub(load_at(53u, data2, 0u), load_at(58u, data2, 0u)));
eqz(sub(load_at(54u, data2, 0u), load_at(59u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x56: Val = load_at(60u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x57: Val = sub(x56, x53);
// zirgen/circuit/recursion/wom.cpp:74
let x58: Val = sub(268435454u, x57);
eqz(mul(x57, x58));
if ((x58) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(56u, data2, 0u), load_at(61u, data2, 0u)));
eqz(sub(load_at(57u, data2, 0u), load_at(62u, data2, 0u)));
eqz(sub(load_at(58u, data2, 0u), load_at(63u, data2, 0u)));
eqz(sub(load_at(59u, data2, 0u), load_at(64u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x59: Val = load_at(65u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x60: Val = sub(x59, x56);
// zirgen/circuit/recursion/wom.cpp:74
let x61: Val = sub(268435454u, x60);
eqz(mul(x60, x61));
if ((x61) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(61u, data2, 0u), load_at(66u, data2, 0u)));
eqz(sub(load_at(62u, data2, 0u), load_at(67u, data2, 0u)));
eqz(sub(load_at(63u, data2, 0u), load_at(68u, data2, 0u)));
eqz(sub(load_at(64u, data2, 0u), load_at(69u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x62: Val = load_at(70u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x63: Val = sub(x62, x59);
// zirgen/circuit/recursion/wom.cpp:74
let x64: Val = sub(268435454u, x63);
eqz(mul(x63, x64));
if ((x64) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(66u, data2, 0u), load_at(71u, data2, 0u)));
eqz(sub(load_at(67u, data2, 0u), load_at(72u, data2, 0u)));
eqz(sub(load_at(68u, data2, 0u), load_at(73u, data2, 0u)));
eqz(sub(load_at(69u, data2, 0u), load_at(74u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x65: Val = load_at(75u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x66: Val = sub(x65, x62);
// zirgen/circuit/recursion/wom.cpp:74
let x67: Val = sub(268435454u, x66);
eqz(mul(x66, x67));
if ((x67) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(71u, data2, 0u), load_at(76u, data2, 0u)));
eqz(sub(load_at(72u, data2, 0u), load_at(77u, data2, 0u)));
eqz(sub(load_at(73u, data2, 0u), load_at(78u, data2, 0u)));
eqz(sub(load_at(74u, data2, 0u), load_at(79u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x68: Val = load_at(80u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x69: Val = sub(x68, x65);
// zirgen/circuit/recursion/wom.cpp:74
let x70: Val = sub(268435454u, x69);
eqz(mul(x69, x70));
if ((x70) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(76u, data2, 0u), load_at(81u, data2, 0u)));
eqz(sub(load_at(77u, data2, 0u), load_at(82u, data2, 0u)));
eqz(sub(load_at(78u, data2, 0u), load_at(83u, data2, 0u)));
eqz(sub(load_at(79u, data2, 0u), load_at(84u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x71: Val = load_at(85u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x72: Val = sub(x71, x68);
// zirgen/circuit/recursion/wom.cpp:74
let x73: Val = sub(268435454u, x72);
eqz(mul(x72, x73));
if ((x73) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(81u, data2, 0u), load_at(86u, data2, 0u)));
eqz(sub(load_at(82u, data2, 0u), load_at(87u, data2, 0u)));
eqz(sub(load_at(83u, data2, 0u), load_at(88u, data2, 0u)));
eqz(sub(load_at(84u, data2, 0u), load_at(89u, data2, 0u)));
}
// zirgen/circuit/recursion/wom.cpp:72
let x74: Val = sub(load_at(0u, data2, 0u), x71);
// zirgen/circuit/recursion/wom.cpp:74
let x75: Val = sub(268435454u, x74);
eqz(mul(x74, x75));
if ((x75) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(86u, data2, 0u), load_at(1u, data2, 0u)));
eqz(sub(load_at(87u, data2, 0u), load_at(2u, data2, 0u)));
eqz(sub(load_at(88u, data2, 0u), load_at(3u, data2, 0u)));
eqz(sub(load_at(89u, data2, 0u), load_at(4u, data2, 0u)));
}
}
if ((load_at(2u, code0, 0u)) != 0u) {
if ((load_at(9u, code0, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:22
store_at(0u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(1u, data2, 0u);
store_at(2u, data2, 0u);
store_at(3u, data2, 0u);
store_at(4u, data2, 0u);
}
if ((load_at(10u, code0, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:72
let x76: Val = sub(load_at(11u, data2, 0u), load_at(0u, data2, 1u));
// zirgen/circuit/recursion/wom.cpp:74
let x77: Val = sub(268435454u, x76);
eqz(mul(x76, x77));
if ((x77) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(1u, data2, 1u), load_at(12u, data2, 0u)));
eqz(sub(load_at(2u, data2, 1u), load_at(13u, data2, 0u)));
eqz(sub(load_at(3u, data2, 1u), load_at(14u, data2, 0u)));
eqz(sub(load_at(4u, data2, 1u), load_at(15u, data2, 0u)));
}
}
if ((load_at(11u, code0, 0u)) != 0u) {
// components/plonk.h:202
let x78_tuple = extern_plonkRead();
let x78: Val = x78_tuple[0u];
let x79: Val = x78_tuple[1u];
let x80: Val = x78_tuple[2u];
let x81: Val = x78_tuple[3u];
let x82: Val = x78_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(26u, data2, x78);
// zirgen/circuit/recursion/wom.cpp:43
store_at(27u, data2, x79);
store_at(28u, data2, x80);
store_at(29u, data2, x81);
store_at(30u, data2, x82);
// components/plonk.h:202
let x83_tuple = extern_plonkRead();
let x83: Val = x83_tuple[0u];
let x84: Val = x83_tuple[1u];
let x85: Val = x83_tuple[2u];
let x86: Val = x83_tuple[3u];
let x87: Val = x83_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(31u, data2, x83);
// zirgen/circuit/recursion/wom.cpp:43
store_at(32u, data2, x84);
store_at(33u, data2, x85);
store_at(34u, data2, x86);
store_at(35u, data2, x87);
// components/plonk.h:202
let x88_tuple = extern_plonkRead();
let x88: Val = x88_tuple[0u];
let x89: Val = x88_tuple[1u];
let x90: Val = x88_tuple[2u];
let x91: Val = x88_tuple[3u];
let x92: Val = x88_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(0u, data2, x88);
// zirgen/circuit/recursion/wom.cpp:43
store_at(1u, data2, x89);
store_at(2u, data2, x90);
store_at(3u, data2, x91);
store_at(4u, data2, x92);
// top(recursion::Top)/mux(Mux)/macro_ops(recursion::MacroOp)/mux(Mux)/bit_and_elem(recursion::BitAndElem)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x93: Val = load_at(26u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x94: Val = sub(x93, load_at(0u, data2, 1u));
// zirgen/circuit/recursion/wom.cpp:74
let x95: Val = sub(268435454u, x94);
eqz(mul(x94, x95));
if ((x95) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(1u, data2, 1u), load_at(27u, data2, 0u)));
eqz(sub(load_at(2u, data2, 1u), load_at(28u, data2, 0u)));
eqz(sub(load_at(3u, data2, 1u), load_at(29u, data2, 0u)));
eqz(sub(load_at(4u, data2, 1u), load_at(30u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/macro_ops(recursion::MacroOp)/mux(Mux)/bit_and_elem(recursion::BitAndElem)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x96: Val = load_at(31u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x97: Val = sub(x96, x93);
// zirgen/circuit/recursion/wom.cpp:74
let x98: Val = sub(268435454u, x97);
eqz(mul(x97, x98));
if ((x98) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(27u, data2, 0u), load_at(32u, data2, 0u)));
eqz(sub(load_at(28u, data2, 0u), load_at(33u, data2, 0u)));
eqz(sub(load_at(29u, data2, 0u), load_at(34u, data2, 0u)));
eqz(sub(load_at(30u, data2, 0u), load_at(35u, data2, 0u)));
}
// zirgen/circuit/recursion/wom.cpp:72
let x99: Val = sub(load_at(0u, data2, 0u), x96);
// zirgen/circuit/recursion/wom.cpp:74
let x100: Val = sub(268435454u, x99);
eqz(mul(x99, x100));
if ((x100) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(32u, data2, 0u), load_at(1u, data2, 0u)));
eqz(sub(load_at(33u, data2, 0u), load_at(2u, data2, 0u)));
eqz(sub(load_at(34u, data2, 0u), load_at(3u, data2, 0u)));
eqz(sub(load_at(35u, data2, 0u), load_at(4u, data2, 0u)));
}
}
if ((load_at(12u, code0, 0u)) != 0u) {
// components/plonk.h:202
let x101_tuple = extern_plonkRead();
let x101: Val = x101_tuple[0u];
let x102: Val = x101_tuple[1u];
let x103: Val = x101_tuple[2u];
let x104: Val = x101_tuple[3u];
let x105: Val = x101_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(26u, data2, x101);
// zirgen/circuit/recursion/wom.cpp:43
store_at(27u, data2, x102);
store_at(28u, data2, x103);
store_at(29u, data2, x104);
store_at(30u, data2, x105);
// components/plonk.h:202
let x106_tuple = extern_plonkRead();
let x106: Val = x106_tuple[0u];
let x107: Val = x106_tuple[1u];
let x108: Val = x106_tuple[2u];
let x109: Val = x106_tuple[3u];
let x110: Val = x106_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(31u, data2, x106);
// zirgen/circuit/recursion/wom.cpp:43
store_at(32u, data2, x107);
store_at(33u, data2, x108);
store_at(34u, data2, x109);
store_at(35u, data2, x110);
// components/plonk.h:202
let x111_tuple = extern_plonkRead();
let x111: Val = x111_tuple[0u];
let x112: Val = x111_tuple[1u];
let x113: Val = x111_tuple[2u];
let x114: Val = x111_tuple[3u];
let x115: Val = x111_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(0u, data2, x111);
// zirgen/circuit/recursion/wom.cpp:43
store_at(1u, data2, x112);
store_at(2u, data2, x113);
store_at(3u, data2, x114);
store_at(4u, data2, x115);
// top(recursion::Top)/mux(Mux)/macro_ops(recursion::MacroOp)/mux(Mux)/bit_op_shorts(recursion::BitOpShorts)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x116: Val = load_at(26u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x117: Val = sub(x116, load_at(0u, data2, 1u));
// zirgen/circuit/recursion/wom.cpp:74
let x118: Val = sub(268435454u, x117);
eqz(mul(x117, x118));
if ((x118) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(1u, data2, 1u), load_at(27u, data2, 0u)));
eqz(sub(load_at(2u, data2, 1u), load_at(28u, data2, 0u)));
eqz(sub(load_at(3u, data2, 1u), load_at(29u, data2, 0u)));
eqz(sub(load_at(4u, data2, 1u), load_at(30u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/macro_ops(recursion::MacroOp)/mux(Mux)/bit_op_shorts(recursion::BitOpShorts)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x119: Val = load_at(31u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x120: Val = sub(x119, x116);
// zirgen/circuit/recursion/wom.cpp:74
let x121: Val = sub(268435454u, x120);
eqz(mul(x120, x121));
if ((x121) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(27u, data2, 0u), load_at(32u, data2, 0u)));
eqz(sub(load_at(28u, data2, 0u), load_at(33u, data2, 0u)));
eqz(sub(load_at(29u, data2, 0u), load_at(34u, data2, 0u)));
eqz(sub(load_at(30u, data2, 0u), load_at(35u, data2, 0u)));
}
// zirgen/circuit/recursion/wom.cpp:72
let x122: Val = sub(load_at(0u, data2, 0u), x119);
// zirgen/circuit/recursion/wom.cpp:74
let x123: Val = sub(268435454u, x122);
eqz(mul(x122, x123));
if ((x123) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(32u, data2, 0u), load_at(1u, data2, 0u)));
eqz(sub(load_at(33u, data2, 0u), load_at(2u, data2, 0u)));
eqz(sub(load_at(34u, data2, 0u), load_at(3u, data2, 0u)));
eqz(sub(load_at(35u, data2, 0u), load_at(4u, data2, 0u)));
}
}
if ((load_at(13u, code0, 0u)) != 0u) {
// components/plonk.h:202
let x124_tuple = extern_plonkRead();
let x124: Val = x124_tuple[0u];
let x125: Val = x124_tuple[1u];
let x126: Val = x124_tuple[2u];
let x127: Val = x124_tuple[3u];
let x128: Val = x124_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(21u, data2, x124);
// zirgen/circuit/recursion/wom.cpp:43
store_at(22u, data2, x125);
store_at(23u, data2, x126);
store_at(24u, data2, x127);
store_at(25u, data2, x128);
// components/plonk.h:202
let x129_tuple = extern_plonkRead();
let x129: Val = x129_tuple[0u];
let x130: Val = x129_tuple[1u];
let x131: Val = x129_tuple[2u];
let x132: Val = x129_tuple[3u];
let x133: Val = x129_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(0u, data2, x129);
// zirgen/circuit/recursion/wom.cpp:43
store_at(1u, data2, x130);
store_at(2u, data2, x131);
store_at(3u, data2, x132);
store_at(4u, data2, x133);
// top(recursion::Top)/mux(Mux)/macro_ops(recursion::MacroOp)/mux(Mux)/sha_init(recursion::ShaWrap)/sha_cycle(recursion::ShaCycle)/recursion::WomBody/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x134: Val = load_at(21u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x135: Val = sub(x134, load_at(0u, data2, 1u));
// zirgen/circuit/recursion/wom.cpp:74
let x136: Val = sub(268435454u, x135);
eqz(mul(x135, x136));
if ((x136) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(1u, data2, 1u), load_at(22u, data2, 0u)));
eqz(sub(load_at(2u, data2, 1u), load_at(23u, data2, 0u)));
eqz(sub(load_at(3u, data2, 1u), load_at(24u, data2, 0u)));
eqz(sub(load_at(4u, data2, 1u), load_at(25u, data2, 0u)));
}
// zirgen/circuit/recursion/wom.cpp:72
let x137: Val = sub(load_at(0u, data2, 0u), x134);
// zirgen/circuit/recursion/wom.cpp:74
let x138: Val = sub(268435454u, x137);
eqz(mul(x137, x138));
if ((x138) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(22u, data2, 0u), load_at(1u, data2, 0u)));
eqz(sub(load_at(23u, data2, 0u), load_at(2u, data2, 0u)));
eqz(sub(load_at(24u, data2, 0u), load_at(3u, data2, 0u)));
eqz(sub(load_at(25u, data2, 0u), load_at(4u, data2, 0u)));
}
}
if ((load_at(14u, code0, 0u)) != 0u) {
// components/plonk.h:202
let x139_tuple = extern_plonkRead();
let x139: Val = x139_tuple[0u];
let x140: Val = x139_tuple[1u];
let x141: Val = x139_tuple[2u];
let x142: Val = x139_tuple[3u];
let x143: Val = x139_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(21u, data2, x139);
// zirgen/circuit/recursion/wom.cpp:43
store_at(22u, data2, x140);
store_at(23u, data2, x141);
store_at(24u, data2, x142);
store_at(25u, data2, x143);
// components/plonk.h:202
let x144_tuple = extern_plonkRead();
let x144: Val = x144_tuple[0u];
let x145: Val = x144_tuple[1u];
let x146: Val = x144_tuple[2u];
let x147: Val = x144_tuple[3u];
let x148: Val = x144_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(0u, data2, x144);
// zirgen/circuit/recursion/wom.cpp:43
store_at(1u, data2, x145);
store_at(2u, data2, x146);
store_at(3u, data2, x147);
store_at(4u, data2, x148);
// top(recursion::Top)/mux(Mux)/macro_ops(recursion::MacroOp)/mux(Mux)/sha_fini(recursion::ShaWrap)/sha_cycle(recursion::ShaCycle)/recursion::WomBody/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x149: Val = load_at(21u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x150: Val = sub(x149, load_at(0u, data2, 1u));
// zirgen/circuit/recursion/wom.cpp:74
let x151: Val = sub(268435454u, x150);
eqz(mul(x150, x151));
if ((x151) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(1u, data2, 1u), load_at(22u, data2, 0u)));
eqz(sub(load_at(2u, data2, 1u), load_at(23u, data2, 0u)));
eqz(sub(load_at(3u, data2, 1u), load_at(24u, data2, 0u)));
eqz(sub(load_at(4u, data2, 1u), load_at(25u, data2, 0u)));
}
// zirgen/circuit/recursion/wom.cpp:72
let x152: Val = sub(load_at(0u, data2, 0u), x149);
// zirgen/circuit/recursion/wom.cpp:74
let x153: Val = sub(268435454u, x152);
eqz(mul(x152, x153));
if ((x153) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(22u, data2, 0u), load_at(1u, data2, 0u)));
eqz(sub(load_at(23u, data2, 0u), load_at(2u, data2, 0u)));
eqz(sub(load_at(24u, data2, 0u), load_at(3u, data2, 0u)));
eqz(sub(load_at(25u, data2, 0u), load_at(4u, data2, 0u)));
}
}
if ((load_at(15u, code0, 0u)) != 0u) {
// components/plonk.h:202
let x154_tuple = extern_plonkRead();
let x154: Val = x154_tuple[0u];
let x155: Val = x154_tuple[1u];
let x156: Val = x154_tuple[2u];
let x157: Val = x154_tuple[3u];
let x158: Val = x154_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(21u, data2, x154);
// zirgen/circuit/recursion/wom.cpp:43
store_at(22u, data2, x155);
store_at(23u, data2, x156);
store_at(24u, data2, x157);
store_at(25u, data2, x158);
// components/plonk.h:202
let x159_tuple = extern_plonkRead();
let x159: Val = x159_tuple[0u];
let x160: Val = x159_tuple[1u];
let x161: Val = x159_tuple[2u];
let x162: Val = x159_tuple[3u];
let x163: Val = x159_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(0u, data2, x159);
// zirgen/circuit/recursion/wom.cpp:43
store_at(1u, data2, x160);
store_at(2u, data2, x161);
store_at(3u, data2, x162);
store_at(4u, data2, x163);
// top(recursion::Top)/mux(Mux)/macro_ops(recursion::MacroOp)/mux(Mux)/sha_load(recursion::ShaWrap)/sha_cycle(recursion::ShaCycle)/recursion::WomBody/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x164: Val = load_at(21u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x165: Val = sub(x164, load_at(0u, data2, 1u));
// zirgen/circuit/recursion/wom.cpp:74
let x166: Val = sub(268435454u, x165);
eqz(mul(x165, x166));
if ((x166) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(1u, data2, 1u), load_at(22u, data2, 0u)));
eqz(sub(load_at(2u, data2, 1u), load_at(23u, data2, 0u)));
eqz(sub(load_at(3u, data2, 1u), load_at(24u, data2, 0u)));
eqz(sub(load_at(4u, data2, 1u), load_at(25u, data2, 0u)));
}
// zirgen/circuit/recursion/wom.cpp:72
let x167: Val = sub(load_at(0u, data2, 0u), x164);
// zirgen/circuit/recursion/wom.cpp:74
let x168: Val = sub(268435454u, x167);
eqz(mul(x167, x168));
if ((x168) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(22u, data2, 0u), load_at(1u, data2, 0u)));
eqz(sub(load_at(23u, data2, 0u), load_at(2u, data2, 0u)));
eqz(sub(load_at(24u, data2, 0u), load_at(3u, data2, 0u)));
eqz(sub(load_at(25u, data2, 0u), load_at(4u, data2, 0u)));
}
}
if ((load_at(16u, code0, 0u)) != 0u) {
// components/plonk.h:202
let x169_tuple = extern_plonkRead();
let x169: Val = x169_tuple[0u];
let x170: Val = x169_tuple[1u];
let x171: Val = x169_tuple[2u];
let x172: Val = x169_tuple[3u];
let x173: Val = x169_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(21u, data2, x169);
// zirgen/circuit/recursion/wom.cpp:43
store_at(22u, data2, x170);
store_at(23u, data2, x171);
store_at(24u, data2, x172);
store_at(25u, data2, x173);
// components/plonk.h:202
let x174_tuple = extern_plonkRead();
let x174: Val = x174_tuple[0u];
let x175: Val = x174_tuple[1u];
let x176: Val = x174_tuple[2u];
let x177: Val = x174_tuple[3u];
let x178: Val = x174_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(0u, data2, x174);
// zirgen/circuit/recursion/wom.cpp:43
store_at(1u, data2, x175);
store_at(2u, data2, x176);
store_at(3u, data2, x177);
store_at(4u, data2, x178);
// top(recursion::Top)/mux(Mux)/macro_ops(recursion::MacroOp)/mux(Mux)/sha_mix(recursion::ShaWrap)/sha_cycle(recursion::ShaCycle)/recursion::WomBody/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x179: Val = load_at(21u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x180: Val = sub(x179, load_at(0u, data2, 1u));
// zirgen/circuit/recursion/wom.cpp:74
let x181: Val = sub(268435454u, x180);
eqz(mul(x180, x181));
if ((x181) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(1u, data2, 1u), load_at(22u, data2, 0u)));
eqz(sub(load_at(2u, data2, 1u), load_at(23u, data2, 0u)));
eqz(sub(load_at(3u, data2, 1u), load_at(24u, data2, 0u)));
eqz(sub(load_at(4u, data2, 1u), load_at(25u, data2, 0u)));
}
// zirgen/circuit/recursion/wom.cpp:72
let x182: Val = sub(load_at(0u, data2, 0u), x179);
// zirgen/circuit/recursion/wom.cpp:74
let x183: Val = sub(268435454u, x182);
eqz(mul(x182, x183));
if ((x183) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(22u, data2, 0u), load_at(1u, data2, 0u)));
eqz(sub(load_at(23u, data2, 0u), load_at(2u, data2, 0u)));
eqz(sub(load_at(24u, data2, 0u), load_at(3u, data2, 0u)));
eqz(sub(load_at(25u, data2, 0u), load_at(4u, data2, 0u)));
}
}
if ((load_at(17u, code0, 0u)) != 0u) {
// components/plonk.h:202
let x184_tuple = extern_plonkRead();
let x184: Val = x184_tuple[0u];
let x185: Val = x184_tuple[1u];
let x186: Val = x184_tuple[2u];
let x187: Val = x184_tuple[3u];
let x188: Val = x184_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(35u, data2, x184);
// zirgen/circuit/recursion/wom.cpp:43
store_at(36u, data2, x185);
store_at(37u, data2, x186);
store_at(38u, data2, x187);
store_at(39u, data2, x188);
// components/plonk.h:202
let x189_tuple = extern_plonkRead();
let x189: Val = x189_tuple[0u];
let x190: Val = x189_tuple[1u];
let x191: Val = x189_tuple[2u];
let x192: Val = x189_tuple[3u];
let x193: Val = x189_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(40u, data2, x189);
// zirgen/circuit/recursion/wom.cpp:43
store_at(41u, data2, x190);
store_at(42u, data2, x191);
store_at(43u, data2, x192);
store_at(44u, data2, x193);
// components/plonk.h:202
let x194_tuple = extern_plonkRead();
let x194: Val = x194_tuple[0u];
let x195: Val = x194_tuple[1u];
let x196: Val = x194_tuple[2u];
let x197: Val = x194_tuple[3u];
let x198: Val = x194_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(45u, data2, x194);
// zirgen/circuit/recursion/wom.cpp:43
store_at(46u, data2, x195);
store_at(47u, data2, x196);
store_at(48u, data2, x197);
store_at(49u, data2, x198);
// components/plonk.h:202
let x199_tuple = extern_plonkRead();
let x199: Val = x199_tuple[0u];
let x200: Val = x199_tuple[1u];
let x201: Val = x199_tuple[2u];
let x202: Val = x199_tuple[3u];
let x203: Val = x199_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(0u, data2, x199);
// zirgen/circuit/recursion/wom.cpp:43
store_at(1u, data2, x200);
store_at(2u, data2, x201);
store_at(3u, data2, x202);
store_at(4u, data2, x203);
// top(recursion::Top)/mux(Mux)/macro_ops(recursion::MacroOp)/mux(Mux)/set_global(recursion::SetGlobal)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x204: Val = load_at(35u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x205: Val = sub(x204, load_at(0u, data2, 1u));
// zirgen/circuit/recursion/wom.cpp:74
let x206: Val = sub(268435454u, x205);
eqz(mul(x205, x206));
if ((x206) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(1u, data2, 1u), load_at(36u, data2, 0u)));
eqz(sub(load_at(2u, data2, 1u), load_at(37u, data2, 0u)));
eqz(sub(load_at(3u, data2, 1u), load_at(38u, data2, 0u)));
eqz(sub(load_at(4u, data2, 1u), load_at(39u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/macro_ops(recursion::MacroOp)/mux(Mux)/set_global(recursion::SetGlobal)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x207: Val = load_at(40u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x208: Val = sub(x207, x204);
// zirgen/circuit/recursion/wom.cpp:74
let x209: Val = sub(268435454u, x208);
eqz(mul(x208, x209));
if ((x209) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(36u, data2, 0u), load_at(41u, data2, 0u)));
eqz(sub(load_at(37u, data2, 0u), load_at(42u, data2, 0u)));
eqz(sub(load_at(38u, data2, 0u), load_at(43u, data2, 0u)));
eqz(sub(load_at(39u, data2, 0u), load_at(44u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/macro_ops(recursion::MacroOp)/mux(Mux)/set_global(recursion::SetGlobal)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x210: Val = load_at(45u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x211: Val = sub(x210, x207);
// zirgen/circuit/recursion/wom.cpp:74
let x212: Val = sub(268435454u, x211);
eqz(mul(x211, x212));
if ((x212) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(41u, data2, 0u), load_at(46u, data2, 0u)));
eqz(sub(load_at(42u, data2, 0u), load_at(47u, data2, 0u)));
eqz(sub(load_at(43u, data2, 0u), load_at(48u, data2, 0u)));
eqz(sub(load_at(44u, data2, 0u), load_at(49u, data2, 0u)));
}
// zirgen/circuit/recursion/wom.cpp:72
let x213: Val = sub(load_at(0u, data2, 0u), x210);
// zirgen/circuit/recursion/wom.cpp:74
let x214: Val = sub(268435454u, x213);
eqz(mul(x213, x214));
if ((x214) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(46u, data2, 0u), load_at(1u, data2, 0u)));
eqz(sub(load_at(47u, data2, 0u), load_at(2u, data2, 0u)));
eqz(sub(load_at(48u, data2, 0u), load_at(3u, data2, 0u)));
eqz(sub(load_at(49u, data2, 0u), load_at(4u, data2, 0u)));
}
}
}
if ((load_at(3u, code0, 0u)) != 0u) {
// components/plonk.h:202
let x215_tuple = extern_plonkRead();
let x215: Val = x215_tuple[0u];
let x216: Val = x215_tuple[1u];
let x217: Val = x215_tuple[2u];
let x218: Val = x215_tuple[3u];
let x219: Val = x215_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(50u, data2, x215);
// zirgen/circuit/recursion/wom.cpp:43
store_at(51u, data2, x216);
store_at(52u, data2, x217);
store_at(53u, data2, x218);
store_at(54u, data2, x219);
// components/plonk.h:202
let x220_tuple = extern_plonkRead();
let x220: Val = x220_tuple[0u];
let x221: Val = x220_tuple[1u];
let x222: Val = x220_tuple[2u];
let x223: Val = x220_tuple[3u];
let x224: Val = x220_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(55u, data2, x220);
// zirgen/circuit/recursion/wom.cpp:43
store_at(56u, data2, x221);
store_at(57u, data2, x222);
store_at(58u, data2, x223);
store_at(59u, data2, x224);
// components/plonk.h:202
let x225_tuple = extern_plonkRead();
let x225: Val = x225_tuple[0u];
let x226: Val = x225_tuple[1u];
let x227: Val = x225_tuple[2u];
let x228: Val = x225_tuple[3u];
let x229: Val = x225_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(60u, data2, x225);
// zirgen/circuit/recursion/wom.cpp:43
store_at(61u, data2, x226);
store_at(62u, data2, x227);
store_at(63u, data2, x228);
store_at(64u, data2, x229);
// components/plonk.h:202
let x230_tuple = extern_plonkRead();
let x230: Val = x230_tuple[0u];
let x231: Val = x230_tuple[1u];
let x232: Val = x230_tuple[2u];
let x233: Val = x230_tuple[3u];
let x234: Val = x230_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(65u, data2, x230);
// zirgen/circuit/recursion/wom.cpp:43
store_at(66u, data2, x231);
store_at(67u, data2, x232);
store_at(68u, data2, x233);
store_at(69u, data2, x234);
// components/plonk.h:202
let x235_tuple = extern_plonkRead();
let x235: Val = x235_tuple[0u];
let x236: Val = x235_tuple[1u];
let x237: Val = x235_tuple[2u];
let x238: Val = x235_tuple[3u];
let x239: Val = x235_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(70u, data2, x235);
// zirgen/circuit/recursion/wom.cpp:43
store_at(71u, data2, x236);
store_at(72u, data2, x237);
store_at(73u, data2, x238);
store_at(74u, data2, x239);
// components/plonk.h:202
let x240_tuple = extern_plonkRead();
let x240: Val = x240_tuple[0u];
let x241: Val = x240_tuple[1u];
let x242: Val = x240_tuple[2u];
let x243: Val = x240_tuple[3u];
let x244: Val = x240_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(75u, data2, x240);
// zirgen/circuit/recursion/wom.cpp:43
store_at(76u, data2, x241);
store_at(77u, data2, x242);
store_at(78u, data2, x243);
store_at(79u, data2, x244);
// components/plonk.h:202
let x245_tuple = extern_plonkRead();
let x245: Val = x245_tuple[0u];
let x246: Val = x245_tuple[1u];
let x247: Val = x245_tuple[2u];
let x248: Val = x245_tuple[3u];
let x249: Val = x245_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(80u, data2, x245);
// zirgen/circuit/recursion/wom.cpp:43
store_at(81u, data2, x246);
store_at(82u, data2, x247);
store_at(83u, data2, x248);
store_at(84u, data2, x249);
// components/plonk.h:202
let x250_tuple = extern_plonkRead();
let x250: Val = x250_tuple[0u];
let x251: Val = x250_tuple[1u];
let x252: Val = x250_tuple[2u];
let x253: Val = x250_tuple[3u];
let x254: Val = x250_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(85u, data2, x250);
// zirgen/circuit/recursion/wom.cpp:43
store_at(86u, data2, x251);
store_at(87u, data2, x252);
store_at(88u, data2, x253);
store_at(89u, data2, x254);
// components/plonk.h:202
let x255_tuple = extern_plonkRead();
let x255: Val = x255_tuple[0u];
let x256: Val = x255_tuple[1u];
let x257: Val = x255_tuple[2u];
let x258: Val = x255_tuple[3u];
let x259: Val = x255_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(0u, data2, x255);
// zirgen/circuit/recursion/wom.cpp:43
store_at(1u, data2, x256);
store_at(2u, data2, x257);
store_at(3u, data2, x258);
store_at(4u, data2, x259);
// top(recursion::Top)/mux(Mux)/poseidon2_load(recursion::Poseidon2Load)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x260: Val = load_at(50u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x261: Val = sub(x260, load_at(0u, data2, 1u));
// zirgen/circuit/recursion/wom.cpp:74
let x262: Val = sub(268435454u, x261);
eqz(mul(x261, x262));
if ((x262) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(1u, data2, 1u), load_at(51u, data2, 0u)));
eqz(sub(load_at(2u, data2, 1u), load_at(52u, data2, 0u)));
eqz(sub(load_at(3u, data2, 1u), load_at(53u, data2, 0u)));
eqz(sub(load_at(4u, data2, 1u), load_at(54u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/poseidon2_load(recursion::Poseidon2Load)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x263: Val = load_at(55u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x264: Val = sub(x263, x260);
// zirgen/circuit/recursion/wom.cpp:74
let x265: Val = sub(268435454u, x264);
eqz(mul(x264, x265));
if ((x265) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(51u, data2, 0u), load_at(56u, data2, 0u)));
eqz(sub(load_at(52u, data2, 0u), load_at(57u, data2, 0u)));
eqz(sub(load_at(53u, data2, 0u), load_at(58u, data2, 0u)));
eqz(sub(load_at(54u, data2, 0u), load_at(59u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/poseidon2_load(recursion::Poseidon2Load)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x266: Val = load_at(60u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x267: Val = sub(x266, x263);
// zirgen/circuit/recursion/wom.cpp:74
let x268: Val = sub(268435454u, x267);
eqz(mul(x267, x268));
if ((x268) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(56u, data2, 0u), load_at(61u, data2, 0u)));
eqz(sub(load_at(57u, data2, 0u), load_at(62u, data2, 0u)));
eqz(sub(load_at(58u, data2, 0u), load_at(63u, data2, 0u)));
eqz(sub(load_at(59u, data2, 0u), load_at(64u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/poseidon2_load(recursion::Poseidon2Load)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x269: Val = load_at(65u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x270: Val = sub(x269, x266);
// zirgen/circuit/recursion/wom.cpp:74
let x271: Val = sub(268435454u, x270);
eqz(mul(x270, x271));
if ((x271) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(61u, data2, 0u), load_at(66u, data2, 0u)));
eqz(sub(load_at(62u, data2, 0u), load_at(67u, data2, 0u)));
eqz(sub(load_at(63u, data2, 0u), load_at(68u, data2, 0u)));
eqz(sub(load_at(64u, data2, 0u), load_at(69u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/poseidon2_load(recursion::Poseidon2Load)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x272: Val = load_at(70u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x273: Val = sub(x272, x269);
// zirgen/circuit/recursion/wom.cpp:74
let x274: Val = sub(268435454u, x273);
eqz(mul(x273, x274));
if ((x274) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(66u, data2, 0u), load_at(71u, data2, 0u)));
eqz(sub(load_at(67u, data2, 0u), load_at(72u, data2, 0u)));
eqz(sub(load_at(68u, data2, 0u), load_at(73u, data2, 0u)));
eqz(sub(load_at(69u, data2, 0u), load_at(74u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/poseidon2_load(recursion::Poseidon2Load)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x275: Val = load_at(75u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x276: Val = sub(x275, x272);
// zirgen/circuit/recursion/wom.cpp:74
let x277: Val = sub(268435454u, x276);
eqz(mul(x276, x277));
if ((x277) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(71u, data2, 0u), load_at(76u, data2, 0u)));
eqz(sub(load_at(72u, data2, 0u), load_at(77u, data2, 0u)));
eqz(sub(load_at(73u, data2, 0u), load_at(78u, data2, 0u)));
eqz(sub(load_at(74u, data2, 0u), load_at(79u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/poseidon2_load(recursion::Poseidon2Load)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x278: Val = load_at(80u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x279: Val = sub(x278, x275);
// zirgen/circuit/recursion/wom.cpp:74
let x280: Val = sub(268435454u, x279);
eqz(mul(x279, x280));
if ((x280) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(76u, data2, 0u), load_at(81u, data2, 0u)));
eqz(sub(load_at(77u, data2, 0u), load_at(82u, data2, 0u)));
eqz(sub(load_at(78u, data2, 0u), load_at(83u, data2, 0u)));
eqz(sub(load_at(79u, data2, 0u), load_at(84u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/poseidon2_load(recursion::Poseidon2Load)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x281: Val = load_at(85u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x282: Val = sub(x281, x278);
// zirgen/circuit/recursion/wom.cpp:74
let x283: Val = sub(268435454u, x282);
eqz(mul(x282, x283));
if ((x283) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(81u, data2, 0u), load_at(86u, data2, 0u)));
eqz(sub(load_at(82u, data2, 0u), load_at(87u, data2, 0u)));
eqz(sub(load_at(83u, data2, 0u), load_at(88u, data2, 0u)));
eqz(sub(load_at(84u, data2, 0u), load_at(89u, data2, 0u)));
}
// zirgen/circuit/recursion/wom.cpp:72
let x284: Val = sub(load_at(0u, data2, 0u), x281);
// zirgen/circuit/recursion/wom.cpp:74
let x285: Val = sub(268435454u, x284);
eqz(mul(x284, x285));
if ((x285) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(86u, data2, 0u), load_at(1u, data2, 0u)));
eqz(sub(load_at(87u, data2, 0u), load_at(2u, data2, 0u)));
eqz(sub(load_at(88u, data2, 0u), load_at(3u, data2, 0u)));
eqz(sub(load_at(89u, data2, 0u), load_at(4u, data2, 0u)));
}
}
if ((load_at(4u, code0, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:41
store_at(0u, data2, load_at(0u, data2, 1u));
// zirgen/circuit/recursion/wom.cpp:43
store_at(1u, data2, load_at(1u, data2, 1u));
store_at(2u, data2, load_at(2u, data2, 1u));
store_at(3u, data2, load_at(3u, data2, 1u));
store_at(4u, data2, load_at(4u, data2, 1u));
}
if ((load_at(5u, code0, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:41
store_at(0u, data2, load_at(0u, data2, 1u));
// zirgen/circuit/recursion/wom.cpp:43
store_at(1u, data2, load_at(1u, data2, 1u));
store_at(2u, data2, load_at(2u, data2, 1u));
store_at(3u, data2, load_at(3u, data2, 1u));
store_at(4u, data2, load_at(4u, data2, 1u));
}
if ((load_at(6u, code0, 0u)) != 0u) {
// components/plonk.h:202
let x286_tuple = extern_plonkRead();
let x286: Val = x286_tuple[0u];
let x287: Val = x286_tuple[1u];
let x288: Val = x286_tuple[2u];
let x289: Val = x286_tuple[3u];
let x290: Val = x286_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(50u, data2, x286);
// zirgen/circuit/recursion/wom.cpp:43
store_at(51u, data2, x287);
store_at(52u, data2, x288);
store_at(53u, data2, x289);
store_at(54u, data2, x290);
// components/plonk.h:202
let x291_tuple = extern_plonkRead();
let x291: Val = x291_tuple[0u];
let x292: Val = x291_tuple[1u];
let x293: Val = x291_tuple[2u];
let x294: Val = x291_tuple[3u];
let x295: Val = x291_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(55u, data2, x291);
// zirgen/circuit/recursion/wom.cpp:43
store_at(56u, data2, x292);
store_at(57u, data2, x293);
store_at(58u, data2, x294);
store_at(59u, data2, x295);
// components/plonk.h:202
let x296_tuple = extern_plonkRead();
let x296: Val = x296_tuple[0u];
let x297: Val = x296_tuple[1u];
let x298: Val = x296_tuple[2u];
let x299: Val = x296_tuple[3u];
let x300: Val = x296_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(60u, data2, x296);
// zirgen/circuit/recursion/wom.cpp:43
store_at(61u, data2, x297);
store_at(62u, data2, x298);
store_at(63u, data2, x299);
store_at(64u, data2, x300);
// components/plonk.h:202
let x301_tuple = extern_plonkRead();
let x301: Val = x301_tuple[0u];
let x302: Val = x301_tuple[1u];
let x303: Val = x301_tuple[2u];
let x304: Val = x301_tuple[3u];
let x305: Val = x301_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(65u, data2, x301);
// zirgen/circuit/recursion/wom.cpp:43
store_at(66u, data2, x302);
store_at(67u, data2, x303);
store_at(68u, data2, x304);
store_at(69u, data2, x305);
// components/plonk.h:202
let x306_tuple = extern_plonkRead();
let x306: Val = x306_tuple[0u];
let x307: Val = x306_tuple[1u];
let x308: Val = x306_tuple[2u];
let x309: Val = x306_tuple[3u];
let x310: Val = x306_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(70u, data2, x306);
// zirgen/circuit/recursion/wom.cpp:43
store_at(71u, data2, x307);
store_at(72u, data2, x308);
store_at(73u, data2, x309);
store_at(74u, data2, x310);
// components/plonk.h:202
let x311_tuple = extern_plonkRead();
let x311: Val = x311_tuple[0u];
let x312: Val = x311_tuple[1u];
let x313: Val = x311_tuple[2u];
let x314: Val = x311_tuple[3u];
let x315: Val = x311_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(75u, data2, x311);
// zirgen/circuit/recursion/wom.cpp:43
store_at(76u, data2, x312);
store_at(77u, data2, x313);
store_at(78u, data2, x314);
store_at(79u, data2, x315);
// components/plonk.h:202
let x316_tuple = extern_plonkRead();
let x316: Val = x316_tuple[0u];
let x317: Val = x316_tuple[1u];
let x318: Val = x316_tuple[2u];
let x319: Val = x316_tuple[3u];
let x320: Val = x316_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(80u, data2, x316);
// zirgen/circuit/recursion/wom.cpp:43
store_at(81u, data2, x317);
store_at(82u, data2, x318);
store_at(83u, data2, x319);
store_at(84u, data2, x320);
// components/plonk.h:202
let x321_tuple = extern_plonkRead();
let x321: Val = x321_tuple[0u];
let x322: Val = x321_tuple[1u];
let x323: Val = x321_tuple[2u];
let x324: Val = x321_tuple[3u];
let x325: Val = x321_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(85u, data2, x321);
// zirgen/circuit/recursion/wom.cpp:43
store_at(86u, data2, x322);
store_at(87u, data2, x323);
store_at(88u, data2, x324);
store_at(89u, data2, x325);
// components/plonk.h:202
let x326_tuple = extern_plonkRead();
let x326: Val = x326_tuple[0u];
let x327: Val = x326_tuple[1u];
let x328: Val = x326_tuple[2u];
let x329: Val = x326_tuple[3u];
let x330: Val = x326_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(0u, data2, x326);
// zirgen/circuit/recursion/wom.cpp:43
store_at(1u, data2, x327);
store_at(2u, data2, x328);
store_at(3u, data2, x329);
store_at(4u, data2, x330);
// top(recursion::Top)/mux(Mux)/poseidon2_store(recursion::Poseidon2Store)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x331: Val = load_at(50u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x332: Val = sub(x331, load_at(0u, data2, 1u));
// zirgen/circuit/recursion/wom.cpp:74
let x333: Val = sub(268435454u, x332);
eqz(mul(x332, x333));
if ((x333) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(1u, data2, 1u), load_at(51u, data2, 0u)));
eqz(sub(load_at(2u, data2, 1u), load_at(52u, data2, 0u)));
eqz(sub(load_at(3u, data2, 1u), load_at(53u, data2, 0u)));
eqz(sub(load_at(4u, data2, 1u), load_at(54u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/poseidon2_store(recursion::Poseidon2Store)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x334: Val = load_at(55u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x335: Val = sub(x334, x331);
// zirgen/circuit/recursion/wom.cpp:74
let x336: Val = sub(268435454u, x335);
eqz(mul(x335, x336));
if ((x336) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(51u, data2, 0u), load_at(56u, data2, 0u)));
eqz(sub(load_at(52u, data2, 0u), load_at(57u, data2, 0u)));
eqz(sub(load_at(53u, data2, 0u), load_at(58u, data2, 0u)));
eqz(sub(load_at(54u, data2, 0u), load_at(59u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/poseidon2_store(recursion::Poseidon2Store)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x337: Val = load_at(60u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x338: Val = sub(x337, x334);
// zirgen/circuit/recursion/wom.cpp:74
let x339: Val = sub(268435454u, x338);
eqz(mul(x338, x339));
if ((x339) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(56u, data2, 0u), load_at(61u, data2, 0u)));
eqz(sub(load_at(57u, data2, 0u), load_at(62u, data2, 0u)));
eqz(sub(load_at(58u, data2, 0u), load_at(63u, data2, 0u)));
eqz(sub(load_at(59u, data2, 0u), load_at(64u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/poseidon2_store(recursion::Poseidon2Store)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x340: Val = load_at(65u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x341: Val = sub(x340, x337);
// zirgen/circuit/recursion/wom.cpp:74
let x342: Val = sub(268435454u, x341);
eqz(mul(x341, x342));
if ((x342) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(61u, data2, 0u), load_at(66u, data2, 0u)));
eqz(sub(load_at(62u, data2, 0u), load_at(67u, data2, 0u)));
eqz(sub(load_at(63u, data2, 0u), load_at(68u, data2, 0u)));
eqz(sub(load_at(64u, data2, 0u), load_at(69u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/poseidon2_store(recursion::Poseidon2Store)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x343: Val = load_at(70u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x344: Val = sub(x343, x340);
// zirgen/circuit/recursion/wom.cpp:74
let x345: Val = sub(268435454u, x344);
eqz(mul(x344, x345));
if ((x345) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(66u, data2, 0u), load_at(71u, data2, 0u)));
eqz(sub(load_at(67u, data2, 0u), load_at(72u, data2, 0u)));
eqz(sub(load_at(68u, data2, 0u), load_at(73u, data2, 0u)));
eqz(sub(load_at(69u, data2, 0u), load_at(74u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/poseidon2_store(recursion::Poseidon2Store)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x346: Val = load_at(75u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x347: Val = sub(x346, x343);
// zirgen/circuit/recursion/wom.cpp:74
let x348: Val = sub(268435454u, x347);
eqz(mul(x347, x348));
if ((x348) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(71u, data2, 0u), load_at(76u, data2, 0u)));
eqz(sub(load_at(72u, data2, 0u), load_at(77u, data2, 0u)));
eqz(sub(load_at(73u, data2, 0u), load_at(78u, data2, 0u)));
eqz(sub(load_at(74u, data2, 0u), load_at(79u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/poseidon2_store(recursion::Poseidon2Store)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x349: Val = load_at(80u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x350: Val = sub(x349, x346);
// zirgen/circuit/recursion/wom.cpp:74
let x351: Val = sub(268435454u, x350);
eqz(mul(x350, x351));
if ((x351) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(76u, data2, 0u), load_at(81u, data2, 0u)));
eqz(sub(load_at(77u, data2, 0u), load_at(82u, data2, 0u)));
eqz(sub(load_at(78u, data2, 0u), load_at(83u, data2, 0u)));
eqz(sub(load_at(79u, data2, 0u), load_at(84u, data2, 0u)));
}
// top(recursion::Top)/mux(Mux)/poseidon2_store(recursion::Poseidon2Store)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x352: Val = load_at(85u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x353: Val = sub(x352, x349);
// zirgen/circuit/recursion/wom.cpp:74
let x354: Val = sub(268435454u, x353);
eqz(mul(x353, x354));
if ((x354) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(81u, data2, 0u), load_at(86u, data2, 0u)));
eqz(sub(load_at(82u, data2, 0u), load_at(87u, data2, 0u)));
eqz(sub(load_at(83u, data2, 0u), load_at(88u, data2, 0u)));
eqz(sub(load_at(84u, data2, 0u), load_at(89u, data2, 0u)));
}
// zirgen/circuit/recursion/wom.cpp:72
let x355: Val = sub(load_at(0u, data2, 0u), x352);
// zirgen/circuit/recursion/wom.cpp:74
let x356: Val = sub(268435454u, x355);
eqz(mul(x355, x356));
if ((x356) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(86u, data2, 0u), load_at(1u, data2, 0u)));
eqz(sub(load_at(87u, data2, 0u), load_at(2u, data2, 0u)));
eqz(sub(load_at(88u, data2, 0u), load_at(3u, data2, 0u)));
eqz(sub(load_at(89u, data2, 0u), load_at(4u, data2, 0u)));
}
}
if ((load_at(7u, code0, 0u)) != 0u) {
// components/plonk.h:202
let x357_tuple = extern_plonkRead();
let x357: Val = x357_tuple[0u];
let x358: Val = x357_tuple[1u];
let x359: Val = x357_tuple[2u];
let x360: Val = x357_tuple[3u];
let x361: Val = x357_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(15u, data2, x357);
// zirgen/circuit/recursion/wom.cpp:43
store_at(16u, data2, x358);
store_at(17u, data2, x359);
store_at(18u, data2, x360);
store_at(19u, data2, x361);
// components/plonk.h:202
let x362_tuple = extern_plonkRead();
let x362: Val = x362_tuple[0u];
let x363: Val = x362_tuple[1u];
let x364: Val = x362_tuple[2u];
let x365: Val = x362_tuple[3u];
let x366: Val = x362_tuple[4u];
// zirgen/circuit/recursion/wom.cpp:41
store_at(0u, data2, x362);
// zirgen/circuit/recursion/wom.cpp:43
store_at(1u, data2, x363);
store_at(2u, data2, x364);
store_at(3u, data2, x365);
store_at(4u, data2, x366);
// top(recursion::Top)/mux(Mux)/checked_bytes(recursion::CheckedBytes)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/addr(Reg)(compiler/edsl/edsl.h:129)
let x367: Val = load_at(15u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:72
let x368: Val = sub(x367, load_at(0u, data2, 1u));
// zirgen/circuit/recursion/wom.cpp:74
let x369: Val = sub(268435454u, x368);
eqz(mul(x368, x369));
if ((x369) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(1u, data2, 1u), load_at(16u, data2, 0u)));
eqz(sub(load_at(2u, data2, 1u), load_at(17u, data2, 0u)));
eqz(sub(load_at(3u, data2, 1u), load_at(18u, data2, 0u)));
eqz(sub(load_at(4u, data2, 1u), load_at(19u, data2, 0u)));
}
// zirgen/circuit/recursion/wom.cpp:72
let x370: Val = sub(load_at(0u, data2, 0u), x367);
// zirgen/circuit/recursion/wom.cpp:74
let x371: Val = sub(268435454u, x370);
eqz(mul(x370, x371));
if ((x371) != 0u) {
// zirgen/circuit/recursion/wom.cpp:78
eqz(sub(load_at(16u, data2, 0u), load_at(1u, data2, 0u)));
eqz(sub(load_at(17u, data2, 0u), load_at(2u, data2, 0u)));
eqz(sub(load_at(18u, data2, 0u), load_at(3u, data2, 0u)));
eqz(sub(load_at(19u, data2, 0u), load_at(4u, data2, 0u)));
}
}
return 0u;
}
