// AUTO-GENERATED by zirgen EDSL WGSL spike; pruned to the micro_ops exec family.
fn recursion(code0: u32, out1: u32, data2: u32, mix3: u32, accum4: u32) -> Val {
// top(recursion::Top)/code(recursion::Code)/select(OneHot)/micro_ops(Reg)(components/mux.h:59)
let x5: Val = load_at(1u, code0, 0u);
if ((x5) != 0u) {
// top(recursion::Top)/code(recursion::Code)/inst(Mux)/micro_ops(recursion::MicroInsts)/inst[0](recursion::MicroInst)/opcode(Reg)(compiler/edsl/component.h:164)
let x6: Val = load_at(8u, code0, 0u);
// top(recursion::Top)/code(recursion::Code)/write_addr(Reg)(zirgen/circuit/recursion/top.cpp:33)
let x7: Val = load_at(0u, code0, 0u);
// components/onehot.h:47
store_at(90u, data2, isz(x6));
store_at(91u, data2, isz(sub(x6, 268435454u)));
store_at(92u, data2, isz(sub(x6, 536870908u)));
store_at(93u, data2, isz(sub(x6, 805306362u)));
store_at(94u, data2, isz(sub(x6, 1073741816u)));
store_at(95u, data2, isz(sub(x6, 1342177270u)));
store_at(96u, data2, isz(sub(x6, 1610612724u)));
store_at(97u, data2, isz(sub(x6, 1879048178u)));
store_at(98u, data2, isz(sub(x6, 134217711u)));
store_at(99u, data2, isz(sub(x6, 402653165u)));
store_at(100u, data2, isz(sub(x6, 671088619u)));
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/op[0](recursion::MicroOp)/decode(OneHot)/inv(Reg)(compiler/edsl/edsl.h:129)
let x8: Val = load_at(94u, data2, 0u);
// top(recursion::Top)/code(recursion::Code)/inst(Mux)/micro_ops(recursion::MicroInsts)/inst[0](recursion::MicroInst)/operand[0](Reg)(zirgen/circuit/recursion/micro.cpp:24)
let x9: Val = load_at(9u, code0, 0u);
// top(recursion::Top)/code(recursion::Code)/inst(Mux)/micro_ops(recursion::MicroInsts)/inst[0](recursion::MicroInst)/operand[2](Reg)(zirgen/circuit/recursion/micro.cpp:26)
let x10: Val = load_at(11u, code0, 0u);
// top(recursion::Top)/code(recursion::Code)/inst(Mux)/micro_ops(recursion::MicroInsts)/inst[0](recursion::MicroInst)/operand[1](Reg)(zirgen/circuit/recursion/micro.cpp:25)
let x11: Val = load_at(10u, code0, 0u);
if ((load_at(90u, data2, 0u)) != 0u) {
// compiler/edsl/edsl.h:328
extern_noop();
// zirgen/circuit/recursion/wom.cpp:22
store_at(5u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(6u, data2, 0u);
store_at(7u, data2, 0u);
store_at(8u, data2, 0u);
store_at(9u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:22
store_at(10u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(11u, data2, 0u);
store_at(12u, data2, 0u);
store_at(13u, data2, 0u);
store_at(14u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:97
store_at(15u, data2, x7);
// zirgen/circuit/recursion/wom.cpp:61
store_at(16u, data2, x9);
store_at(17u, data2, x11);
store_at(18u, data2, x10);
store_at(19u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(15u, data2, 0u), load_at(16u, data2, 0u), load_at(17u, data2, 0u), load_at(18u, data2, 0u), load_at(19u, data2, 0u));
}
if ((load_at(91u, data2, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x12_tuple = extern_womRead(x9);
let x12: Val = x12_tuple[0u];
let x13: Val = x12_tuple[1u];
let x14: Val = x12_tuple[2u];
let x15: Val = x12_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(6u, data2, x12);
store_at(7u, data2, x13);
store_at(8u, data2, x14);
store_at(9u, data2, x15);
// zirgen/circuit/recursion/wom.cpp:92
store_at(5u, data2, x9);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x16: Val = load_at(6u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x17: Val = load_at(7u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x18: Val = load_at(8u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x19: Val = load_at(9u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:91
let x20_tuple = extern_womRead(x11);
let x20: Val = x20_tuple[0u];
let x21: Val = x20_tuple[1u];
let x22: Val = x20_tuple[2u];
let x23: Val = x20_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(11u, data2, x20);
store_at(12u, data2, x21);
store_at(13u, data2, x22);
store_at(14u, data2, x23);
// zirgen/circuit/recursion/wom.cpp:92
store_at(10u, data2, x11);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x24: Val = load_at(11u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x25: Val = load_at(12u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x26: Val = load_at(13u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x27: Val = load_at(14u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:97
store_at(15u, data2, x7);
// zirgen/circuit/recursion/wom.cpp:61
store_at(16u, data2, add(x16, x24));
store_at(17u, data2, add(x17, x25));
store_at(18u, data2, add(x18, x26));
store_at(19u, data2, add(x19, x27));
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(15u, data2, 0u), load_at(16u, data2, 0u), load_at(17u, data2, 0u), load_at(18u, data2, 0u), load_at(19u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((load_at(92u, data2, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x28_tuple = extern_womRead(x9);
let x28: Val = x28_tuple[0u];
let x29: Val = x28_tuple[1u];
let x30: Val = x28_tuple[2u];
let x31: Val = x28_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(6u, data2, x28);
store_at(7u, data2, x29);
store_at(8u, data2, x30);
store_at(9u, data2, x31);
// zirgen/circuit/recursion/wom.cpp:92
store_at(5u, data2, x9);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x32: Val = load_at(6u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x33: Val = load_at(7u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x34: Val = load_at(8u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x35: Val = load_at(9u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:91
let x36_tuple = extern_womRead(x11);
let x36: Val = x36_tuple[0u];
let x37: Val = x36_tuple[1u];
let x38: Val = x36_tuple[2u];
let x39: Val = x36_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(11u, data2, x36);
store_at(12u, data2, x37);
store_at(13u, data2, x38);
store_at(14u, data2, x39);
// zirgen/circuit/recursion/wom.cpp:92
store_at(10u, data2, x11);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x40: Val = load_at(11u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x41: Val = load_at(12u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x42: Val = load_at(13u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x43: Val = load_at(14u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:97
store_at(15u, data2, x7);
// zirgen/circuit/recursion/wom.cpp:61
store_at(16u, data2, sub(x32, x40));
store_at(17u, data2, sub(x33, x41));
store_at(18u, data2, sub(x34, x42));
store_at(19u, data2, sub(x35, x43));
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(15u, data2, 0u), load_at(16u, data2, 0u), load_at(17u, data2, 0u), load_at(18u, data2, 0u), load_at(19u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((load_at(93u, data2, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x44_tuple = extern_womRead(x9);
let x44: Val = x44_tuple[0u];
let x45: Val = x44_tuple[1u];
let x46: Val = x44_tuple[2u];
let x47: Val = x44_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(6u, data2, x44);
store_at(7u, data2, x45);
store_at(8u, data2, x46);
store_at(9u, data2, x47);
// zirgen/circuit/recursion/wom.cpp:92
store_at(5u, data2, x9);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x48: Val = load_at(6u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x49: Val = load_at(7u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x50: Val = load_at(8u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x51: Val = load_at(9u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:91
let x52_tuple = extern_womRead(x11);
let x52: Val = x52_tuple[0u];
let x53: Val = x52_tuple[1u];
let x54: Val = x52_tuple[2u];
let x55: Val = x52_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(11u, data2, x52);
store_at(12u, data2, x53);
store_at(13u, data2, x54);
store_at(14u, data2, x55);
// zirgen/circuit/recursion/wom.cpp:92
store_at(10u, data2, x11);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x56: Val = load_at(11u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x57: Val = load_at(12u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x58: Val = load_at(13u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x59: Val = load_at(14u, data2, 0u);
// zirgen/circuit/recursion/micro.cpp:50
let x60: Val = mul(add(mul(x50, x59), mul(x51, x58)), 1073741848u);
let x61: Val = add(add(mul(x48, x58), mul(x49, x57)), mul(x50, x56));
let x62: Val = add(add(mul(x48, x59), mul(x49, x58)), mul(x50, x57));
let x63: Val = add(add(mul(x49, x59), mul(x50, x58)), mul(x51, x57));
let x64: Val = add(add(mul(x48, x57), mul(x49, x56)), x60);
// zirgen/circuit/recursion/wom.cpp:97
store_at(15u, data2, x7);
// zirgen/circuit/recursion/wom.cpp:61
store_at(16u, data2, add(mul(x48, x56), mul(x63, 1073741848u)));
store_at(17u, data2, x64);
store_at(18u, data2, add(x61, mul(mul(x51, x59), 1073741848u)));
store_at(19u, data2, add(x62, mul(x51, x56)));
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(15u, data2, 0u), load_at(16u, data2, 0u), load_at(17u, data2, 0u), load_at(18u, data2, 0u), load_at(19u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((mul(x8, x11)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x65_tuple = extern_womRead(x9);
let x65: Val = x65_tuple[0u];
let x66: Val = x65_tuple[1u];
let x67: Val = x65_tuple[2u];
let x68: Val = x65_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(6u, data2, x65);
store_at(7u, data2, x66);
store_at(8u, data2, x67);
store_at(9u, data2, x68);
// zirgen/circuit/recursion/wom.cpp:92
store_at(5u, data2, x9);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x69: Val = load_at(6u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x70: Val = load_at(7u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x71: Val = load_at(8u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x72: Val = load_at(9u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:22
store_at(10u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(11u, data2, 0u);
store_at(12u, data2, 0u);
store_at(13u, data2, 0u);
store_at(14u, data2, 0u);
// zirgen/circuit/recursion/micro.cpp:56
let x73: Val = add(sub(mul(x69, add(x71, x71)), mul(x70, x70)), mul(mul(x72, x72), 939524073u));
let x74: Val = mul(sub(mul(x70, add(x72, x72)), mul(x71, x71)), 939524073u);
let x75: Val = add(mul(x69, x69), x74);
let x76: Val = add(mul(x75, x75), mul(mul(x73, 939524073u), x73));
let x77: Val = inv_0(x76);
let x78: Val = mul(x75, x77);
let x79: Val = mul(x73, x77);
let x80: Val = sub(mul(neg_0(x70), x78), mul(mul(x72, 939524073u), x79));
let x81: Val = add(mul(x69, x78), mul(mul(x71, 939524073u), x79));
let x82: Val = add(mul(neg_0(x69), x79), mul(x71, x78));
// zirgen/circuit/recursion/wom.cpp:97
store_at(15u, data2, x7);
// zirgen/circuit/recursion/wom.cpp:61
store_at(16u, data2, x81);
store_at(17u, data2, x80);
store_at(18u, data2, x82);
store_at(19u, data2, sub(mul(x70, x79), mul(x72, x78)));
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(15u, data2, 0u), load_at(16u, data2, 0u), load_at(17u, data2, 0u), load_at(18u, data2, 0u), load_at(19u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
// zirgen/circuit/recursion/micro.cpp:60
let x83: Val = sub(268435454u, x11);
if ((mul(x8, x83)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x84_tuple = extern_womRead(x9);
let x84: Val = x84_tuple[0u];
let x85: Val = x84_tuple[1u];
let x86: Val = x84_tuple[2u];
let x87: Val = x84_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(6u, data2, x84);
store_at(7u, data2, x85);
store_at(8u, data2, x86);
store_at(9u, data2, x87);
// zirgen/circuit/recursion/wom.cpp:92
store_at(5u, data2, x9);
// zirgen/circuit/recursion/wom.cpp:22
store_at(10u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(11u, data2, 0u);
store_at(12u, data2, 0u);
store_at(13u, data2, 0u);
store_at(14u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x88: Val = load_at(6u, data2, 0u);
// zirgen/circuit/recursion/micro.cpp:65
store_at(101u, data2, inv_0(x88));
// zirgen/circuit/recursion/micro.cpp:66
let x89: Val = sub(268435454u, mul(load_at(101u, data2, 0u), x88));
// zirgen/circuit/recursion/wom.cpp:97
store_at(15u, data2, x7);
// zirgen/circuit/recursion/wom.cpp:61
store_at(16u, data2, x89);
store_at(17u, data2, 0u);
store_at(18u, data2, 0u);
store_at(19u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(15u, data2, 0u), load_at(16u, data2, 0u), load_at(17u, data2, 0u), load_at(18u, data2, 0u), load_at(19u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((load_at(95u, data2, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x90_tuple = extern_womRead(x9);
let x90: Val = x90_tuple[0u];
let x91: Val = x90_tuple[1u];
let x92: Val = x90_tuple[2u];
let x93: Val = x90_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(6u, data2, x90);
store_at(7u, data2, x91);
store_at(8u, data2, x92);
store_at(9u, data2, x93);
// zirgen/circuit/recursion/wom.cpp:92
store_at(5u, data2, x9);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x94: Val = load_at(6u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x95: Val = load_at(7u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x96: Val = load_at(8u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x97: Val = load_at(9u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:91
let x98_tuple = extern_womRead(x11);
let x98: Val = x98_tuple[0u];
let x99: Val = x98_tuple[1u];
let x100: Val = x98_tuple[2u];
let x101: Val = x98_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(11u, data2, x98);
store_at(12u, data2, x99);
store_at(13u, data2, x100);
store_at(14u, data2, x101);
// zirgen/circuit/recursion/wom.cpp:92
store_at(10u, data2, x11);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x102: Val = load_at(11u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x103: Val = load_at(12u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x104: Val = load_at(13u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x105: Val = load_at(14u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:97
store_at(15u, data2, x7);
// zirgen/circuit/recursion/wom.cpp:61
store_at(16u, data2, sub(x94, x102));
store_at(17u, data2, sub(x95, x103));
store_at(18u, data2, sub(x96, x104));
store_at(19u, data2, sub(x97, x105));
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(15u, data2, 0u), load_at(16u, data2, 0u), load_at(17u, data2, 0u), load_at(18u, data2, 0u), load_at(19u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((load_at(96u, data2, 0u)) != 0u) {
extern_noop();
// zirgen/circuit/recursion/wom.cpp:22
store_at(5u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(6u, data2, 0u);
store_at(7u, data2, 0u);
store_at(8u, data2, 0u);
store_at(9u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:22
store_at(10u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(11u, data2, 0u);
store_at(12u, data2, 0u);
store_at(13u, data2, 0u);
store_at(14u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:97
store_at(15u, data2, x7);
// zirgen/circuit/recursion/wom.cpp:61
store_at(16u, data2, 0u);
store_at(17u, data2, 0u);
store_at(18u, data2, 0u);
store_at(19u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(15u, data2, 0u), load_at(16u, data2, 0u), load_at(17u, data2, 0u), load_at(18u, data2, 0u), load_at(19u, data2, 0u));
// zirgen/circuit/recursion/micro.cpp:90
extern_readIOPHeader(x9, x11);
}
if ((load_at(97u, data2, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:22
store_at(5u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(6u, data2, 0u);
store_at(7u, data2, 0u);
store_at(8u, data2, 0u);
store_at(9u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:22
store_at(10u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(11u, data2, 0u);
store_at(12u, data2, 0u);
store_at(13u, data2, 0u);
store_at(14u, data2, 0u);
// zirgen/circuit/recursion/micro.cpp:96
let x106_tuple = extern_readIOPBody(x9, x11, x10);
let x106: Val = x106_tuple[0u];
let x107: Val = x106_tuple[1u];
let x108: Val = x106_tuple[2u];
let x109: Val = x106_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:97
store_at(15u, data2, x7);
// zirgen/circuit/recursion/wom.cpp:61
store_at(16u, data2, x106);
store_at(17u, data2, x107);
store_at(18u, data2, x108);
store_at(19u, data2, x109);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(15u, data2, 0u), load_at(16u, data2, 0u), load_at(17u, data2, 0u), load_at(18u, data2, 0u), load_at(19u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((load_at(98u, data2, 0u)) != 0u) {
extern_noop();
// zirgen/circuit/recursion/wom.cpp:91
let x110_tuple = extern_womRead(x9);
let x110: Val = x110_tuple[0u];
let x111: Val = x110_tuple[1u];
let x112: Val = x110_tuple[2u];
let x113: Val = x110_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(6u, data2, x110);
store_at(7u, data2, x111);
store_at(8u, data2, x112);
store_at(9u, data2, x113);
// zirgen/circuit/recursion/wom.cpp:92
store_at(5u, data2, x9);
// zirgen/circuit/recursion/wom.cpp:91
let x114_tuple = extern_womRead(x11);
let x114: Val = x114_tuple[0u];
let x115: Val = x114_tuple[1u];
let x116: Val = x114_tuple[2u];
let x117: Val = x114_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(11u, data2, x114);
store_at(12u, data2, x115);
store_at(13u, data2, x116);
store_at(14u, data2, x117);
// zirgen/circuit/recursion/wom.cpp:92
store_at(10u, data2, x11);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x118: Val = load_at(6u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x119: Val = load_at(7u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x120: Val = load_at(11u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x121: Val = load_at(12u, data2, 0u);
// compiler/edsl/edsl.h:328
extern_noop();
// zirgen/circuit/recursion/micro.cpp:117
let x122: Val = mul(x10, load_at(125u, data2, 1u));
// compiler/edsl/edsl.h:328
extern_noop();
// zirgen/circuit/recursion/micro.cpp:120
let x123: Val = mul(add(mul(x122, 268295646u), x119), 268295646u);
// zirgen/circuit/recursion/micro.cpp:121
let x124: Val = add(mul(add(x123, x118), 268295646u), x121);
// zirgen/circuit/recursion/micro.cpp:122
let x125: Val = add(mul(x124, 268295646u), x120);
// compiler/edsl/edsl.h:328
extern_noop();
// zirgen/circuit/recursion/micro.cpp:124
store_at(101u, data2, x125);
// zirgen/circuit/recursion/wom.cpp:97
store_at(15u, data2, x7);
// zirgen/circuit/recursion/wom.cpp:61
store_at(16u, data2, x125);
store_at(17u, data2, 0u);
store_at(18u, data2, 0u);
store_at(19u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(15u, data2, 0u), load_at(16u, data2, 0u), load_at(17u, data2, 0u), load_at(18u, data2, 0u), load_at(19u, data2, 0u));
}
if ((load_at(99u, data2, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x126_tuple = extern_womRead(x9);
let x126: Val = x126_tuple[0u];
let x127: Val = x126_tuple[1u];
let x128: Val = x126_tuple[2u];
let x129: Val = x126_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(6u, data2, x126);
store_at(7u, data2, x127);
store_at(8u, data2, x128);
store_at(9u, data2, x129);
// zirgen/circuit/recursion/wom.cpp:92
store_at(5u, data2, x9);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x130: Val = load_at(6u, data2, 0u);
// zirgen/circuit/recursion/micro.cpp:129
let x131: Val = add(x11, mul(x10, x130));
// zirgen/circuit/recursion/wom.cpp:91
let x132_tuple = extern_womRead(x131);
let x132: Val = x132_tuple[0u];
let x133: Val = x132_tuple[1u];
let x134: Val = x132_tuple[2u];
let x135: Val = x132_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(11u, data2, x132);
store_at(12u, data2, x133);
store_at(13u, data2, x134);
store_at(14u, data2, x135);
// zirgen/circuit/recursion/wom.cpp:92
store_at(10u, data2, x131);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x136: Val = load_at(11u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x137: Val = load_at(12u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x138: Val = load_at(13u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x139: Val = load_at(14u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:97
store_at(15u, data2, x7);
// zirgen/circuit/recursion/wom.cpp:61
store_at(16u, data2, x136);
store_at(17u, data2, x137);
store_at(18u, data2, x138);
store_at(19u, data2, x139);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(15u, data2, 0u), load_at(16u, data2, 0u), load_at(17u, data2, 0u), load_at(18u, data2, 0u), load_at(19u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((load_at(100u, data2, 0u)) != 0u) {
extern_noop();
// zirgen/circuit/recursion/wom.cpp:91
let x140_tuple = extern_womRead(x9);
let x140: Val = x140_tuple[0u];
let x141: Val = x140_tuple[1u];
let x142: Val = x140_tuple[2u];
let x143: Val = x140_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(6u, data2, x140);
store_at(7u, data2, x141);
store_at(8u, data2, x142);
store_at(9u, data2, x143);
// zirgen/circuit/recursion/wom.cpp:92
store_at(5u, data2, x9);
// zirgen/circuit/recursion/wom.cpp:22
store_at(10u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(11u, data2, 0u);
store_at(12u, data2, 0u);
store_at(13u, data2, 0u);
store_at(14u, data2, 0u);
// zirgen/circuit/recursion/micro.cpp:147
let x144: Val = sub(268435454u, x10);
// zirgen/circuit/recursion/micro.cpp:145
let x145: Val = add(mul(mul(x11, x10), load_at(9u, data2, 0u)), mul(mul(x11, x144), load_at(8u, data2, 0u)));
// zirgen/circuit/recursion/micro.cpp:147
let x146: Val = add(add(x145, mul(mul(x83, x10), load_at(7u, data2, 0u))), mul(mul(x83, x144), load_at(6u, data2, 0u)));
// zirgen/circuit/recursion/wom.cpp:97
store_at(15u, data2, x7);
// zirgen/circuit/recursion/wom.cpp:61
store_at(16u, data2, x146);
store_at(17u, data2, 0u);
store_at(18u, data2, 0u);
store_at(19u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(15u, data2, 0u), load_at(16u, data2, 0u), load_at(17u, data2, 0u), load_at(18u, data2, 0u), load_at(19u, data2, 0u));
}
// zirgen/circuit/recursion/micro.cpp:163
let x147: Val = add(x7, 268435454u);
// top(recursion::Top)/code(recursion::Code)/inst(Mux)/micro_ops(recursion::MicroInsts)/inst[1](recursion::MicroInst)/opcode(Reg)(compiler/edsl/component.h:164)
let x148: Val = load_at(12u, code0, 0u);
// components/onehot.h:47
store_at(102u, data2, isz(x148));
store_at(103u, data2, isz(sub(x148, 268435454u)));
store_at(104u, data2, isz(sub(x148, 536870908u)));
store_at(105u, data2, isz(sub(x148, 805306362u)));
store_at(106u, data2, isz(sub(x148, 1073741816u)));
store_at(107u, data2, isz(sub(x148, 1342177270u)));
store_at(108u, data2, isz(sub(x148, 1610612724u)));
store_at(109u, data2, isz(sub(x148, 1879048178u)));
store_at(110u, data2, isz(sub(x148, 134217711u)));
store_at(111u, data2, isz(sub(x148, 402653165u)));
store_at(112u, data2, isz(sub(x148, 671088619u)));
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/op[1](recursion::MicroOp)/decode(OneHot)/inv(Reg)(compiler/edsl/edsl.h:129)
let x149: Val = load_at(106u, data2, 0u);
// top(recursion::Top)/code(recursion::Code)/inst(Mux)/micro_ops(recursion::MicroInsts)/inst[1](recursion::MicroInst)/operand[0](Reg)(zirgen/circuit/recursion/micro.cpp:24)
let x150: Val = load_at(13u, code0, 0u);
// top(recursion::Top)/code(recursion::Code)/inst(Mux)/micro_ops(recursion::MicroInsts)/inst[1](recursion::MicroInst)/operand[2](Reg)(zirgen/circuit/recursion/micro.cpp:26)
let x151: Val = load_at(15u, code0, 0u);
// top(recursion::Top)/code(recursion::Code)/inst(Mux)/micro_ops(recursion::MicroInsts)/inst[1](recursion::MicroInst)/operand[1](Reg)(zirgen/circuit/recursion/micro.cpp:25)
let x152: Val = load_at(14u, code0, 0u);
if ((load_at(102u, data2, 0u)) != 0u) {
// compiler/edsl/edsl.h:328
extern_noop();
// zirgen/circuit/recursion/wom.cpp:22
store_at(20u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(21u, data2, 0u);
store_at(22u, data2, 0u);
store_at(23u, data2, 0u);
store_at(24u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:22
store_at(25u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(26u, data2, 0u);
store_at(27u, data2, 0u);
store_at(28u, data2, 0u);
store_at(29u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:97
store_at(30u, data2, x147);
// zirgen/circuit/recursion/wom.cpp:61
store_at(31u, data2, x150);
store_at(32u, data2, x152);
store_at(33u, data2, x151);
store_at(34u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(30u, data2, 0u), load_at(31u, data2, 0u), load_at(32u, data2, 0u), load_at(33u, data2, 0u), load_at(34u, data2, 0u));
}
if ((load_at(103u, data2, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x153_tuple = extern_womRead(x150);
let x153: Val = x153_tuple[0u];
let x154: Val = x153_tuple[1u];
let x155: Val = x153_tuple[2u];
let x156: Val = x153_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(21u, data2, x153);
store_at(22u, data2, x154);
store_at(23u, data2, x155);
store_at(24u, data2, x156);
// zirgen/circuit/recursion/wom.cpp:92
store_at(20u, data2, x150);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x157: Val = load_at(21u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x158: Val = load_at(22u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x159: Val = load_at(23u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x160: Val = load_at(24u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:91
let x161_tuple = extern_womRead(x152);
let x161: Val = x161_tuple[0u];
let x162: Val = x161_tuple[1u];
let x163: Val = x161_tuple[2u];
let x164: Val = x161_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(26u, data2, x161);
store_at(27u, data2, x162);
store_at(28u, data2, x163);
store_at(29u, data2, x164);
// zirgen/circuit/recursion/wom.cpp:92
store_at(25u, data2, x152);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x165: Val = load_at(26u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x166: Val = load_at(27u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x167: Val = load_at(28u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x168: Val = load_at(29u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:97
store_at(30u, data2, x147);
// zirgen/circuit/recursion/wom.cpp:61
store_at(31u, data2, add(x157, x165));
store_at(32u, data2, add(x158, x166));
store_at(33u, data2, add(x159, x167));
store_at(34u, data2, add(x160, x168));
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(30u, data2, 0u), load_at(31u, data2, 0u), load_at(32u, data2, 0u), load_at(33u, data2, 0u), load_at(34u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((load_at(104u, data2, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x169_tuple = extern_womRead(x150);
let x169: Val = x169_tuple[0u];
let x170: Val = x169_tuple[1u];
let x171: Val = x169_tuple[2u];
let x172: Val = x169_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(21u, data2, x169);
store_at(22u, data2, x170);
store_at(23u, data2, x171);
store_at(24u, data2, x172);
// zirgen/circuit/recursion/wom.cpp:92
store_at(20u, data2, x150);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x173: Val = load_at(21u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x174: Val = load_at(22u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x175: Val = load_at(23u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x176: Val = load_at(24u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:91
let x177_tuple = extern_womRead(x152);
let x177: Val = x177_tuple[0u];
let x178: Val = x177_tuple[1u];
let x179: Val = x177_tuple[2u];
let x180: Val = x177_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(26u, data2, x177);
store_at(27u, data2, x178);
store_at(28u, data2, x179);
store_at(29u, data2, x180);
// zirgen/circuit/recursion/wom.cpp:92
store_at(25u, data2, x152);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x181: Val = load_at(26u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x182: Val = load_at(27u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x183: Val = load_at(28u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x184: Val = load_at(29u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:97
store_at(30u, data2, x147);
// zirgen/circuit/recursion/wom.cpp:61
store_at(31u, data2, sub(x173, x181));
store_at(32u, data2, sub(x174, x182));
store_at(33u, data2, sub(x175, x183));
store_at(34u, data2, sub(x176, x184));
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(30u, data2, 0u), load_at(31u, data2, 0u), load_at(32u, data2, 0u), load_at(33u, data2, 0u), load_at(34u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((load_at(105u, data2, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x185_tuple = extern_womRead(x150);
let x185: Val = x185_tuple[0u];
let x186: Val = x185_tuple[1u];
let x187: Val = x185_tuple[2u];
let x188: Val = x185_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(21u, data2, x185);
store_at(22u, data2, x186);
store_at(23u, data2, x187);
store_at(24u, data2, x188);
// zirgen/circuit/recursion/wom.cpp:92
store_at(20u, data2, x150);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x189: Val = load_at(21u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x190: Val = load_at(22u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x191: Val = load_at(23u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x192: Val = load_at(24u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:91
let x193_tuple = extern_womRead(x152);
let x193: Val = x193_tuple[0u];
let x194: Val = x193_tuple[1u];
let x195: Val = x193_tuple[2u];
let x196: Val = x193_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(26u, data2, x193);
store_at(27u, data2, x194);
store_at(28u, data2, x195);
store_at(29u, data2, x196);
// zirgen/circuit/recursion/wom.cpp:92
store_at(25u, data2, x152);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x197: Val = load_at(26u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x198: Val = load_at(27u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x199: Val = load_at(28u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x200: Val = load_at(29u, data2, 0u);
// zirgen/circuit/recursion/micro.cpp:50
let x201: Val = mul(add(mul(x191, x200), mul(x192, x199)), 1073741848u);
let x202: Val = add(add(mul(x189, x199), mul(x190, x198)), mul(x191, x197));
let x203: Val = add(add(mul(x189, x200), mul(x190, x199)), mul(x191, x198));
let x204: Val = add(add(mul(x190, x200), mul(x191, x199)), mul(x192, x198));
let x205: Val = add(add(mul(x189, x198), mul(x190, x197)), x201);
// zirgen/circuit/recursion/wom.cpp:97
store_at(30u, data2, x147);
// zirgen/circuit/recursion/wom.cpp:61
store_at(31u, data2, add(mul(x189, x197), mul(x204, 1073741848u)));
store_at(32u, data2, x205);
store_at(33u, data2, add(x202, mul(mul(x192, x200), 1073741848u)));
store_at(34u, data2, add(x203, mul(x192, x197)));
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(30u, data2, 0u), load_at(31u, data2, 0u), load_at(32u, data2, 0u), load_at(33u, data2, 0u), load_at(34u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((mul(x149, x152)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x206_tuple = extern_womRead(x150);
let x206: Val = x206_tuple[0u];
let x207: Val = x206_tuple[1u];
let x208: Val = x206_tuple[2u];
let x209: Val = x206_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(21u, data2, x206);
store_at(22u, data2, x207);
store_at(23u, data2, x208);
store_at(24u, data2, x209);
// zirgen/circuit/recursion/wom.cpp:92
store_at(20u, data2, x150);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x210: Val = load_at(21u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x211: Val = load_at(22u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x212: Val = load_at(23u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x213: Val = load_at(24u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:22
store_at(25u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(26u, data2, 0u);
store_at(27u, data2, 0u);
store_at(28u, data2, 0u);
store_at(29u, data2, 0u);
// zirgen/circuit/recursion/micro.cpp:56
let x214: Val = add(sub(mul(x210, add(x212, x212)), mul(x211, x211)), mul(mul(x213, x213), 939524073u));
let x215: Val = mul(sub(mul(x211, add(x213, x213)), mul(x212, x212)), 939524073u);
let x216: Val = add(mul(x210, x210), x215);
let x217: Val = add(mul(x216, x216), mul(mul(x214, 939524073u), x214));
let x218: Val = inv_0(x217);
let x219: Val = mul(x216, x218);
let x220: Val = mul(x214, x218);
let x221: Val = sub(mul(neg_0(x211), x219), mul(mul(x213, 939524073u), x220));
let x222: Val = add(mul(x210, x219), mul(mul(x212, 939524073u), x220));
let x223: Val = add(mul(neg_0(x210), x220), mul(x212, x219));
// zirgen/circuit/recursion/wom.cpp:97
store_at(30u, data2, x147);
// zirgen/circuit/recursion/wom.cpp:61
store_at(31u, data2, x222);
store_at(32u, data2, x221);
store_at(33u, data2, x223);
store_at(34u, data2, sub(mul(x211, x220), mul(x213, x219)));
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(30u, data2, 0u), load_at(31u, data2, 0u), load_at(32u, data2, 0u), load_at(33u, data2, 0u), load_at(34u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
// zirgen/circuit/recursion/micro.cpp:60
let x224: Val = sub(268435454u, x152);
if ((mul(x149, x224)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x225_tuple = extern_womRead(x150);
let x225: Val = x225_tuple[0u];
let x226: Val = x225_tuple[1u];
let x227: Val = x225_tuple[2u];
let x228: Val = x225_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(21u, data2, x225);
store_at(22u, data2, x226);
store_at(23u, data2, x227);
store_at(24u, data2, x228);
// zirgen/circuit/recursion/wom.cpp:92
store_at(20u, data2, x150);
// zirgen/circuit/recursion/wom.cpp:22
store_at(25u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(26u, data2, 0u);
store_at(27u, data2, 0u);
store_at(28u, data2, 0u);
store_at(29u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x229: Val = load_at(21u, data2, 0u);
// zirgen/circuit/recursion/micro.cpp:65
store_at(113u, data2, inv_0(x229));
// zirgen/circuit/recursion/micro.cpp:66
let x230: Val = sub(268435454u, mul(load_at(113u, data2, 0u), x229));
// zirgen/circuit/recursion/wom.cpp:97
store_at(30u, data2, x147);
// zirgen/circuit/recursion/wom.cpp:61
store_at(31u, data2, x230);
store_at(32u, data2, 0u);
store_at(33u, data2, 0u);
store_at(34u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(30u, data2, 0u), load_at(31u, data2, 0u), load_at(32u, data2, 0u), load_at(33u, data2, 0u), load_at(34u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((load_at(107u, data2, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x231_tuple = extern_womRead(x150);
let x231: Val = x231_tuple[0u];
let x232: Val = x231_tuple[1u];
let x233: Val = x231_tuple[2u];
let x234: Val = x231_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(21u, data2, x231);
store_at(22u, data2, x232);
store_at(23u, data2, x233);
store_at(24u, data2, x234);
// zirgen/circuit/recursion/wom.cpp:92
store_at(20u, data2, x150);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x235: Val = load_at(21u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x236: Val = load_at(22u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x237: Val = load_at(23u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x238: Val = load_at(24u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:91
let x239_tuple = extern_womRead(x152);
let x239: Val = x239_tuple[0u];
let x240: Val = x239_tuple[1u];
let x241: Val = x239_tuple[2u];
let x242: Val = x239_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(26u, data2, x239);
store_at(27u, data2, x240);
store_at(28u, data2, x241);
store_at(29u, data2, x242);
// zirgen/circuit/recursion/wom.cpp:92
store_at(25u, data2, x152);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x243: Val = load_at(26u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x244: Val = load_at(27u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x245: Val = load_at(28u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x246: Val = load_at(29u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:97
store_at(30u, data2, x147);
// zirgen/circuit/recursion/wom.cpp:61
store_at(31u, data2, sub(x235, x243));
store_at(32u, data2, sub(x236, x244));
store_at(33u, data2, sub(x237, x245));
store_at(34u, data2, sub(x238, x246));
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(30u, data2, 0u), load_at(31u, data2, 0u), load_at(32u, data2, 0u), load_at(33u, data2, 0u), load_at(34u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((load_at(108u, data2, 0u)) != 0u) {
extern_noop();
// zirgen/circuit/recursion/wom.cpp:22
store_at(20u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(21u, data2, 0u);
store_at(22u, data2, 0u);
store_at(23u, data2, 0u);
store_at(24u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:22
store_at(25u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(26u, data2, 0u);
store_at(27u, data2, 0u);
store_at(28u, data2, 0u);
store_at(29u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:97
store_at(30u, data2, x147);
// zirgen/circuit/recursion/wom.cpp:61
store_at(31u, data2, 0u);
store_at(32u, data2, 0u);
store_at(33u, data2, 0u);
store_at(34u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(30u, data2, 0u), load_at(31u, data2, 0u), load_at(32u, data2, 0u), load_at(33u, data2, 0u), load_at(34u, data2, 0u));
// zirgen/circuit/recursion/micro.cpp:90
extern_readIOPHeader(x150, x152);
}
if ((load_at(109u, data2, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:22
store_at(20u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(21u, data2, 0u);
store_at(22u, data2, 0u);
store_at(23u, data2, 0u);
store_at(24u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:22
store_at(25u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(26u, data2, 0u);
store_at(27u, data2, 0u);
store_at(28u, data2, 0u);
store_at(29u, data2, 0u);
// zirgen/circuit/recursion/micro.cpp:96
let x247_tuple = extern_readIOPBody(x150, x152, x151);
let x247: Val = x247_tuple[0u];
let x248: Val = x247_tuple[1u];
let x249: Val = x247_tuple[2u];
let x250: Val = x247_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:97
store_at(30u, data2, x147);
// zirgen/circuit/recursion/wom.cpp:61
store_at(31u, data2, x247);
store_at(32u, data2, x248);
store_at(33u, data2, x249);
store_at(34u, data2, x250);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(30u, data2, 0u), load_at(31u, data2, 0u), load_at(32u, data2, 0u), load_at(33u, data2, 0u), load_at(34u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((load_at(110u, data2, 0u)) != 0u) {
extern_noop();
// zirgen/circuit/recursion/wom.cpp:91
let x251_tuple = extern_womRead(x150);
let x251: Val = x251_tuple[0u];
let x252: Val = x251_tuple[1u];
let x253: Val = x251_tuple[2u];
let x254: Val = x251_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(21u, data2, x251);
store_at(22u, data2, x252);
store_at(23u, data2, x253);
store_at(24u, data2, x254);
// zirgen/circuit/recursion/wom.cpp:92
store_at(20u, data2, x150);
// zirgen/circuit/recursion/wom.cpp:91
let x255_tuple = extern_womRead(x152);
let x255: Val = x255_tuple[0u];
let x256: Val = x255_tuple[1u];
let x257: Val = x255_tuple[2u];
let x258: Val = x255_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(26u, data2, x255);
store_at(27u, data2, x256);
store_at(28u, data2, x257);
store_at(29u, data2, x258);
// zirgen/circuit/recursion/wom.cpp:92
store_at(25u, data2, x152);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x259: Val = load_at(21u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x260: Val = load_at(22u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x261: Val = load_at(26u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x262: Val = load_at(27u, data2, 0u);
// compiler/edsl/edsl.h:328
extern_noop();
// zirgen/circuit/recursion/micro.cpp:117
let x263: Val = mul(x151, load_at(101u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
// zirgen/circuit/recursion/micro.cpp:120
let x264: Val = mul(add(mul(x263, 268295646u), x260), 268295646u);
// zirgen/circuit/recursion/micro.cpp:121
let x265: Val = add(mul(add(x264, x259), 268295646u), x262);
// zirgen/circuit/recursion/micro.cpp:122
let x266: Val = add(mul(x265, 268295646u), x261);
// compiler/edsl/edsl.h:328
extern_noop();
// zirgen/circuit/recursion/micro.cpp:124
store_at(113u, data2, x266);
// zirgen/circuit/recursion/wom.cpp:97
store_at(30u, data2, x147);
// zirgen/circuit/recursion/wom.cpp:61
store_at(31u, data2, x266);
store_at(32u, data2, 0u);
store_at(33u, data2, 0u);
store_at(34u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(30u, data2, 0u), load_at(31u, data2, 0u), load_at(32u, data2, 0u), load_at(33u, data2, 0u), load_at(34u, data2, 0u));
}
if ((load_at(111u, data2, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x267_tuple = extern_womRead(x150);
let x267: Val = x267_tuple[0u];
let x268: Val = x267_tuple[1u];
let x269: Val = x267_tuple[2u];
let x270: Val = x267_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(21u, data2, x267);
store_at(22u, data2, x268);
store_at(23u, data2, x269);
store_at(24u, data2, x270);
// zirgen/circuit/recursion/wom.cpp:92
store_at(20u, data2, x150);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x271: Val = load_at(21u, data2, 0u);
// zirgen/circuit/recursion/micro.cpp:129
let x272: Val = add(x152, mul(x151, x271));
// zirgen/circuit/recursion/wom.cpp:91
let x273_tuple = extern_womRead(x272);
let x273: Val = x273_tuple[0u];
let x274: Val = x273_tuple[1u];
let x275: Val = x273_tuple[2u];
let x276: Val = x273_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(26u, data2, x273);
store_at(27u, data2, x274);
store_at(28u, data2, x275);
store_at(29u, data2, x276);
// zirgen/circuit/recursion/wom.cpp:92
store_at(25u, data2, x272);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x277: Val = load_at(26u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x278: Val = load_at(27u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x279: Val = load_at(28u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x280: Val = load_at(29u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:97
store_at(30u, data2, x147);
// zirgen/circuit/recursion/wom.cpp:61
store_at(31u, data2, x277);
store_at(32u, data2, x278);
store_at(33u, data2, x279);
store_at(34u, data2, x280);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(30u, data2, 0u), load_at(31u, data2, 0u), load_at(32u, data2, 0u), load_at(33u, data2, 0u), load_at(34u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((load_at(112u, data2, 0u)) != 0u) {
extern_noop();
// zirgen/circuit/recursion/wom.cpp:91
let x281_tuple = extern_womRead(x150);
let x281: Val = x281_tuple[0u];
let x282: Val = x281_tuple[1u];
let x283: Val = x281_tuple[2u];
let x284: Val = x281_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(21u, data2, x281);
store_at(22u, data2, x282);
store_at(23u, data2, x283);
store_at(24u, data2, x284);
// zirgen/circuit/recursion/wom.cpp:92
store_at(20u, data2, x150);
// zirgen/circuit/recursion/wom.cpp:22
store_at(25u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(26u, data2, 0u);
store_at(27u, data2, 0u);
store_at(28u, data2, 0u);
store_at(29u, data2, 0u);
// zirgen/circuit/recursion/micro.cpp:147
let x285: Val = sub(268435454u, x151);
// zirgen/circuit/recursion/micro.cpp:145
let x286: Val = add(mul(mul(x152, x151), load_at(24u, data2, 0u)), mul(mul(x152, x285), load_at(23u, data2, 0u)));
// zirgen/circuit/recursion/micro.cpp:147
let x287: Val = add(add(x286, mul(mul(x224, x151), load_at(22u, data2, 0u))), mul(mul(x224, x285), load_at(21u, data2, 0u)));
// zirgen/circuit/recursion/wom.cpp:97
store_at(30u, data2, x147);
// zirgen/circuit/recursion/wom.cpp:61
store_at(31u, data2, x287);
store_at(32u, data2, 0u);
store_at(33u, data2, 0u);
store_at(34u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(30u, data2, 0u), load_at(31u, data2, 0u), load_at(32u, data2, 0u), load_at(33u, data2, 0u), load_at(34u, data2, 0u));
}
// zirgen/circuit/recursion/micro.cpp:163
let x288: Val = add(x7, 536870908u);
// top(recursion::Top)/code(recursion::Code)/inst(Mux)/micro_ops(recursion::MicroInsts)/inst[2](recursion::MicroInst)/opcode(Reg)(compiler/edsl/component.h:164)
let x289: Val = load_at(16u, code0, 0u);
// components/onehot.h:47
store_at(114u, data2, isz(x289));
store_at(115u, data2, isz(sub(x289, 268435454u)));
store_at(116u, data2, isz(sub(x289, 536870908u)));
store_at(117u, data2, isz(sub(x289, 805306362u)));
store_at(118u, data2, isz(sub(x289, 1073741816u)));
store_at(119u, data2, isz(sub(x289, 1342177270u)));
store_at(120u, data2, isz(sub(x289, 1610612724u)));
store_at(121u, data2, isz(sub(x289, 1879048178u)));
store_at(122u, data2, isz(sub(x289, 134217711u)));
store_at(123u, data2, isz(sub(x289, 402653165u)));
store_at(124u, data2, isz(sub(x289, 671088619u)));
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/op[2](recursion::MicroOp)/decode(OneHot)/inv(Reg)(compiler/edsl/edsl.h:129)
let x290: Val = load_at(118u, data2, 0u);
// top(recursion::Top)/code(recursion::Code)/inst(Mux)/micro_ops(recursion::MicroInsts)/inst[2](recursion::MicroInst)/operand[0](Reg)(zirgen/circuit/recursion/micro.cpp:24)
let x291: Val = load_at(17u, code0, 0u);
// top(recursion::Top)/code(recursion::Code)/inst(Mux)/micro_ops(recursion::MicroInsts)/inst[2](recursion::MicroInst)/operand[2](Reg)(zirgen/circuit/recursion/micro.cpp:26)
let x292: Val = load_at(19u, code0, 0u);
// top(recursion::Top)/code(recursion::Code)/inst(Mux)/micro_ops(recursion::MicroInsts)/inst[2](recursion::MicroInst)/operand[1](Reg)(zirgen/circuit/recursion/micro.cpp:25)
let x293: Val = load_at(18u, code0, 0u);
if ((load_at(114u, data2, 0u)) != 0u) {
// compiler/edsl/edsl.h:328
extern_noop();
// zirgen/circuit/recursion/wom.cpp:22
store_at(35u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(36u, data2, 0u);
store_at(37u, data2, 0u);
store_at(38u, data2, 0u);
store_at(39u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:22
store_at(40u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(41u, data2, 0u);
store_at(42u, data2, 0u);
store_at(43u, data2, 0u);
store_at(44u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:97
store_at(45u, data2, x288);
// zirgen/circuit/recursion/wom.cpp:61
store_at(46u, data2, x291);
store_at(47u, data2, x293);
store_at(48u, data2, x292);
store_at(49u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(45u, data2, 0u), load_at(46u, data2, 0u), load_at(47u, data2, 0u), load_at(48u, data2, 0u), load_at(49u, data2, 0u));
}
if ((load_at(115u, data2, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x294_tuple = extern_womRead(x291);
let x294: Val = x294_tuple[0u];
let x295: Val = x294_tuple[1u];
let x296: Val = x294_tuple[2u];
let x297: Val = x294_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(36u, data2, x294);
store_at(37u, data2, x295);
store_at(38u, data2, x296);
store_at(39u, data2, x297);
// zirgen/circuit/recursion/wom.cpp:92
store_at(35u, data2, x291);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x298: Val = load_at(36u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x299: Val = load_at(37u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x300: Val = load_at(38u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x301: Val = load_at(39u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:91
let x302_tuple = extern_womRead(x293);
let x302: Val = x302_tuple[0u];
let x303: Val = x302_tuple[1u];
let x304: Val = x302_tuple[2u];
let x305: Val = x302_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(41u, data2, x302);
store_at(42u, data2, x303);
store_at(43u, data2, x304);
store_at(44u, data2, x305);
// zirgen/circuit/recursion/wom.cpp:92
store_at(40u, data2, x293);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x306: Val = load_at(41u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x307: Val = load_at(42u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x308: Val = load_at(43u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x309: Val = load_at(44u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:97
store_at(45u, data2, x288);
// zirgen/circuit/recursion/wom.cpp:61
store_at(46u, data2, add(x298, x306));
store_at(47u, data2, add(x299, x307));
store_at(48u, data2, add(x300, x308));
store_at(49u, data2, add(x301, x309));
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(45u, data2, 0u), load_at(46u, data2, 0u), load_at(47u, data2, 0u), load_at(48u, data2, 0u), load_at(49u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((load_at(116u, data2, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x310_tuple = extern_womRead(x291);
let x310: Val = x310_tuple[0u];
let x311: Val = x310_tuple[1u];
let x312: Val = x310_tuple[2u];
let x313: Val = x310_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(36u, data2, x310);
store_at(37u, data2, x311);
store_at(38u, data2, x312);
store_at(39u, data2, x313);
// zirgen/circuit/recursion/wom.cpp:92
store_at(35u, data2, x291);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x314: Val = load_at(36u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x315: Val = load_at(37u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x316: Val = load_at(38u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x317: Val = load_at(39u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:91
let x318_tuple = extern_womRead(x293);
let x318: Val = x318_tuple[0u];
let x319: Val = x318_tuple[1u];
let x320: Val = x318_tuple[2u];
let x321: Val = x318_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(41u, data2, x318);
store_at(42u, data2, x319);
store_at(43u, data2, x320);
store_at(44u, data2, x321);
// zirgen/circuit/recursion/wom.cpp:92
store_at(40u, data2, x293);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x322: Val = load_at(41u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x323: Val = load_at(42u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x324: Val = load_at(43u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x325: Val = load_at(44u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:97
store_at(45u, data2, x288);
// zirgen/circuit/recursion/wom.cpp:61
store_at(46u, data2, sub(x314, x322));
store_at(47u, data2, sub(x315, x323));
store_at(48u, data2, sub(x316, x324));
store_at(49u, data2, sub(x317, x325));
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(45u, data2, 0u), load_at(46u, data2, 0u), load_at(47u, data2, 0u), load_at(48u, data2, 0u), load_at(49u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((load_at(117u, data2, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x326_tuple = extern_womRead(x291);
let x326: Val = x326_tuple[0u];
let x327: Val = x326_tuple[1u];
let x328: Val = x326_tuple[2u];
let x329: Val = x326_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(36u, data2, x326);
store_at(37u, data2, x327);
store_at(38u, data2, x328);
store_at(39u, data2, x329);
// zirgen/circuit/recursion/wom.cpp:92
store_at(35u, data2, x291);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x330: Val = load_at(36u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x331: Val = load_at(37u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x332: Val = load_at(38u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x333: Val = load_at(39u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:91
let x334_tuple = extern_womRead(x293);
let x334: Val = x334_tuple[0u];
let x335: Val = x334_tuple[1u];
let x336: Val = x334_tuple[2u];
let x337: Val = x334_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(41u, data2, x334);
store_at(42u, data2, x335);
store_at(43u, data2, x336);
store_at(44u, data2, x337);
// zirgen/circuit/recursion/wom.cpp:92
store_at(40u, data2, x293);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x338: Val = load_at(41u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x339: Val = load_at(42u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x340: Val = load_at(43u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x341: Val = load_at(44u, data2, 0u);
// zirgen/circuit/recursion/micro.cpp:50
let x342: Val = mul(add(mul(x332, x341), mul(x333, x340)), 1073741848u);
let x343: Val = add(add(mul(x330, x340), mul(x331, x339)), mul(x332, x338));
let x344: Val = add(add(mul(x330, x341), mul(x331, x340)), mul(x332, x339));
let x345: Val = add(add(mul(x331, x341), mul(x332, x340)), mul(x333, x339));
let x346: Val = add(add(mul(x330, x339), mul(x331, x338)), x342);
// zirgen/circuit/recursion/wom.cpp:97
store_at(45u, data2, x288);
// zirgen/circuit/recursion/wom.cpp:61
store_at(46u, data2, add(mul(x330, x338), mul(x345, 1073741848u)));
store_at(47u, data2, x346);
store_at(48u, data2, add(x343, mul(mul(x333, x341), 1073741848u)));
store_at(49u, data2, add(x344, mul(x333, x338)));
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(45u, data2, 0u), load_at(46u, data2, 0u), load_at(47u, data2, 0u), load_at(48u, data2, 0u), load_at(49u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((mul(x290, x293)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x347_tuple = extern_womRead(x291);
let x347: Val = x347_tuple[0u];
let x348: Val = x347_tuple[1u];
let x349: Val = x347_tuple[2u];
let x350: Val = x347_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(36u, data2, x347);
store_at(37u, data2, x348);
store_at(38u, data2, x349);
store_at(39u, data2, x350);
// zirgen/circuit/recursion/wom.cpp:92
store_at(35u, data2, x291);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x351: Val = load_at(36u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x352: Val = load_at(37u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x353: Val = load_at(38u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x354: Val = load_at(39u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:22
store_at(40u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(41u, data2, 0u);
store_at(42u, data2, 0u);
store_at(43u, data2, 0u);
store_at(44u, data2, 0u);
// zirgen/circuit/recursion/micro.cpp:56
let x355: Val = add(sub(mul(x351, add(x353, x353)), mul(x352, x352)), mul(mul(x354, x354), 939524073u));
let x356: Val = mul(sub(mul(x352, add(x354, x354)), mul(x353, x353)), 939524073u);
let x357: Val = add(mul(x351, x351), x356);
let x358: Val = add(mul(x357, x357), mul(mul(x355, 939524073u), x355));
let x359: Val = inv_0(x358);
let x360: Val = mul(x357, x359);
let x361: Val = mul(x355, x359);
let x362: Val = sub(mul(neg_0(x352), x360), mul(mul(x354, 939524073u), x361));
let x363: Val = add(mul(x351, x360), mul(mul(x353, 939524073u), x361));
let x364: Val = add(mul(neg_0(x351), x361), mul(x353, x360));
// zirgen/circuit/recursion/wom.cpp:97
store_at(45u, data2, x288);
// zirgen/circuit/recursion/wom.cpp:61
store_at(46u, data2, x363);
store_at(47u, data2, x362);
store_at(48u, data2, x364);
store_at(49u, data2, sub(mul(x352, x361), mul(x354, x360)));
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(45u, data2, 0u), load_at(46u, data2, 0u), load_at(47u, data2, 0u), load_at(48u, data2, 0u), load_at(49u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
// zirgen/circuit/recursion/micro.cpp:60
let x365: Val = sub(268435454u, x293);
if ((mul(x290, x365)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x366_tuple = extern_womRead(x291);
let x366: Val = x366_tuple[0u];
let x367: Val = x366_tuple[1u];
let x368: Val = x366_tuple[2u];
let x369: Val = x366_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(36u, data2, x366);
store_at(37u, data2, x367);
store_at(38u, data2, x368);
store_at(39u, data2, x369);
// zirgen/circuit/recursion/wom.cpp:92
store_at(35u, data2, x291);
// zirgen/circuit/recursion/wom.cpp:22
store_at(40u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(41u, data2, 0u);
store_at(42u, data2, 0u);
store_at(43u, data2, 0u);
store_at(44u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x370: Val = load_at(36u, data2, 0u);
// zirgen/circuit/recursion/micro.cpp:65
store_at(125u, data2, inv_0(x370));
// zirgen/circuit/recursion/micro.cpp:66
let x371: Val = sub(268435454u, mul(load_at(125u, data2, 0u), x370));
// zirgen/circuit/recursion/wom.cpp:97
store_at(45u, data2, x288);
// zirgen/circuit/recursion/wom.cpp:61
store_at(46u, data2, x371);
store_at(47u, data2, 0u);
store_at(48u, data2, 0u);
store_at(49u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(45u, data2, 0u), load_at(46u, data2, 0u), load_at(47u, data2, 0u), load_at(48u, data2, 0u), load_at(49u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((load_at(119u, data2, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x372_tuple = extern_womRead(x291);
let x372: Val = x372_tuple[0u];
let x373: Val = x372_tuple[1u];
let x374: Val = x372_tuple[2u];
let x375: Val = x372_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(36u, data2, x372);
store_at(37u, data2, x373);
store_at(38u, data2, x374);
store_at(39u, data2, x375);
// zirgen/circuit/recursion/wom.cpp:92
store_at(35u, data2, x291);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x376: Val = load_at(36u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x377: Val = load_at(37u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x378: Val = load_at(38u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x379: Val = load_at(39u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:91
let x380_tuple = extern_womRead(x293);
let x380: Val = x380_tuple[0u];
let x381: Val = x380_tuple[1u];
let x382: Val = x380_tuple[2u];
let x383: Val = x380_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(41u, data2, x380);
store_at(42u, data2, x381);
store_at(43u, data2, x382);
store_at(44u, data2, x383);
// zirgen/circuit/recursion/wom.cpp:92
store_at(40u, data2, x293);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x384: Val = load_at(41u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x385: Val = load_at(42u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x386: Val = load_at(43u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x387: Val = load_at(44u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:97
store_at(45u, data2, x288);
// zirgen/circuit/recursion/wom.cpp:61
store_at(46u, data2, sub(x376, x384));
store_at(47u, data2, sub(x377, x385));
store_at(48u, data2, sub(x378, x386));
store_at(49u, data2, sub(x379, x387));
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(45u, data2, 0u), load_at(46u, data2, 0u), load_at(47u, data2, 0u), load_at(48u, data2, 0u), load_at(49u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((load_at(120u, data2, 0u)) != 0u) {
extern_noop();
// zirgen/circuit/recursion/wom.cpp:22
store_at(35u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(36u, data2, 0u);
store_at(37u, data2, 0u);
store_at(38u, data2, 0u);
store_at(39u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:22
store_at(40u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(41u, data2, 0u);
store_at(42u, data2, 0u);
store_at(43u, data2, 0u);
store_at(44u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:97
store_at(45u, data2, x288);
// zirgen/circuit/recursion/wom.cpp:61
store_at(46u, data2, 0u);
store_at(47u, data2, 0u);
store_at(48u, data2, 0u);
store_at(49u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(45u, data2, 0u), load_at(46u, data2, 0u), load_at(47u, data2, 0u), load_at(48u, data2, 0u), load_at(49u, data2, 0u));
// zirgen/circuit/recursion/micro.cpp:90
extern_readIOPHeader(x291, x293);
}
if ((load_at(121u, data2, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:22
store_at(35u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(36u, data2, 0u);
store_at(37u, data2, 0u);
store_at(38u, data2, 0u);
store_at(39u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:22
store_at(40u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(41u, data2, 0u);
store_at(42u, data2, 0u);
store_at(43u, data2, 0u);
store_at(44u, data2, 0u);
// zirgen/circuit/recursion/micro.cpp:96
let x388_tuple = extern_readIOPBody(x291, x293, x292);
let x388: Val = x388_tuple[0u];
let x389: Val = x388_tuple[1u];
let x390: Val = x388_tuple[2u];
let x391: Val = x388_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:97
store_at(45u, data2, x288);
// zirgen/circuit/recursion/wom.cpp:61
store_at(46u, data2, x388);
store_at(47u, data2, x389);
store_at(48u, data2, x390);
store_at(49u, data2, x391);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(45u, data2, 0u), load_at(46u, data2, 0u), load_at(47u, data2, 0u), load_at(48u, data2, 0u), load_at(49u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((load_at(122u, data2, 0u)) != 0u) {
extern_noop();
// zirgen/circuit/recursion/wom.cpp:91
let x392_tuple = extern_womRead(x291);
let x392: Val = x392_tuple[0u];
let x393: Val = x392_tuple[1u];
let x394: Val = x392_tuple[2u];
let x395: Val = x392_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(36u, data2, x392);
store_at(37u, data2, x393);
store_at(38u, data2, x394);
store_at(39u, data2, x395);
// zirgen/circuit/recursion/wom.cpp:92
store_at(35u, data2, x291);
// zirgen/circuit/recursion/wom.cpp:91
let x396_tuple = extern_womRead(x293);
let x396: Val = x396_tuple[0u];
let x397: Val = x396_tuple[1u];
let x398: Val = x396_tuple[2u];
let x399: Val = x396_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(41u, data2, x396);
store_at(42u, data2, x397);
store_at(43u, data2, x398);
store_at(44u, data2, x399);
// zirgen/circuit/recursion/wom.cpp:92
store_at(40u, data2, x293);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x400: Val = load_at(36u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x401: Val = load_at(37u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x402: Val = load_at(41u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x403: Val = load_at(42u, data2, 0u);
// compiler/edsl/edsl.h:328
extern_noop();
// zirgen/circuit/recursion/micro.cpp:117
let x404: Val = mul(x292, load_at(113u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
// zirgen/circuit/recursion/micro.cpp:120
let x405: Val = mul(add(mul(x404, 268295646u), x401), 268295646u);
// zirgen/circuit/recursion/micro.cpp:121
let x406: Val = add(mul(add(x405, x400), 268295646u), x403);
// zirgen/circuit/recursion/micro.cpp:122
let x407: Val = add(mul(x406, 268295646u), x402);
// compiler/edsl/edsl.h:328
extern_noop();
// zirgen/circuit/recursion/micro.cpp:124
store_at(125u, data2, x407);
// zirgen/circuit/recursion/wom.cpp:97
store_at(45u, data2, x288);
// zirgen/circuit/recursion/wom.cpp:61
store_at(46u, data2, x407);
store_at(47u, data2, 0u);
store_at(48u, data2, 0u);
store_at(49u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(45u, data2, 0u), load_at(46u, data2, 0u), load_at(47u, data2, 0u), load_at(48u, data2, 0u), load_at(49u, data2, 0u));
}
if ((load_at(123u, data2, 0u)) != 0u) {
// zirgen/circuit/recursion/wom.cpp:91
let x408_tuple = extern_womRead(x291);
let x408: Val = x408_tuple[0u];
let x409: Val = x408_tuple[1u];
let x410: Val = x408_tuple[2u];
let x411: Val = x408_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(36u, data2, x408);
store_at(37u, data2, x409);
store_at(38u, data2, x410);
store_at(39u, data2, x411);
// zirgen/circuit/recursion/wom.cpp:92
store_at(35u, data2, x291);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x412: Val = load_at(36u, data2, 0u);
// zirgen/circuit/recursion/micro.cpp:129
let x413: Val = add(x293, mul(x292, x412));
// zirgen/circuit/recursion/wom.cpp:91
let x414_tuple = extern_womRead(x413);
let x414: Val = x414_tuple[0u];
let x415: Val = x414_tuple[1u];
let x416: Val = x414_tuple[2u];
let x417: Val = x414_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(41u, data2, x414);
store_at(42u, data2, x415);
store_at(43u, data2, x416);
store_at(44u, data2, x417);
// zirgen/circuit/recursion/wom.cpp:92
store_at(40u, data2, x413);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[0](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x418: Val = load_at(41u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[1](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x419: Val = load_at(42u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[2](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x420: Val = load_at(43u, data2, 0u);
// top(recursion::Top)/mux(Mux)/micro_ops(recursion::MicroOps)/wom_body(recursion::WomBody)/plonk_body(PlonkBody)/recursion::impl::WomPlonkElement/data[3](Reg)(zirgen/circuit/recursion/wom.cpp:54)
let x421: Val = load_at(44u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:97
store_at(45u, data2, x288);
// zirgen/circuit/recursion/wom.cpp:61
store_at(46u, data2, x418);
store_at(47u, data2, x419);
store_at(48u, data2, x420);
store_at(49u, data2, x421);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(45u, data2, 0u), load_at(46u, data2, 0u), load_at(47u, data2, 0u), load_at(48u, data2, 0u), load_at(49u, data2, 0u));
// compiler/edsl/edsl.h:328
extern_noop();
}
if ((load_at(124u, data2, 0u)) != 0u) {
extern_noop();
// zirgen/circuit/recursion/wom.cpp:91
let x422_tuple = extern_womRead(x291);
let x422: Val = x422_tuple[0u];
let x423: Val = x422_tuple[1u];
let x424: Val = x422_tuple[2u];
let x425: Val = x422_tuple[3u];
// zirgen/circuit/recursion/wom.cpp:61
store_at(36u, data2, x422);
store_at(37u, data2, x423);
store_at(38u, data2, x424);
store_at(39u, data2, x425);
// zirgen/circuit/recursion/wom.cpp:92
store_at(35u, data2, x291);
// zirgen/circuit/recursion/wom.cpp:22
store_at(40u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:61
store_at(41u, data2, 0u);
store_at(42u, data2, 0u);
store_at(43u, data2, 0u);
store_at(44u, data2, 0u);
// zirgen/circuit/recursion/micro.cpp:147
let x426: Val = sub(268435454u, x292);
// zirgen/circuit/recursion/micro.cpp:145
let x427: Val = add(mul(mul(x293, x292), load_at(39u, data2, 0u)), mul(mul(x293, x426), load_at(38u, data2, 0u)));
// zirgen/circuit/recursion/micro.cpp:147
let x428: Val = add(add(x427, mul(mul(x365, x292), load_at(37u, data2, 0u))), mul(mul(x365, x426), load_at(36u, data2, 0u)));
// zirgen/circuit/recursion/wom.cpp:97
store_at(45u, data2, x288);
// zirgen/circuit/recursion/wom.cpp:61
store_at(46u, data2, x428);
store_at(47u, data2, 0u);
store_at(48u, data2, 0u);
store_at(49u, data2, 0u);
// zirgen/circuit/recursion/wom.cpp:99
extern_womWrite(load_at(45u, data2, 0u), load_at(46u, data2, 0u), load_at(47u, data2, 0u), load_at(48u, data2, 0u), load_at(49u, data2, 0u));
}
}
if ((x5) != 0u) {
// components/plonk.h:192
extern_plonkWrite(load_at(5u, data2, 0u), load_at(6u, data2, 0u), load_at(7u, data2, 0u), load_at(8u, data2, 0u), load_at(9u, data2, 0u));
extern_plonkWrite(load_at(10u, data2, 0u), load_at(11u, data2, 0u), load_at(12u, data2, 0u), load_at(13u, data2, 0u), load_at(14u, data2, 0u));
extern_plonkWrite(load_at(15u, data2, 0u), load_at(16u, data2, 0u), load_at(17u, data2, 0u), load_at(18u, data2, 0u), load_at(19u, data2, 0u));
extern_plonkWrite(load_at(20u, data2, 0u), load_at(21u, data2, 0u), load_at(22u, data2, 0u), load_at(23u, data2, 0u), load_at(24u, data2, 0u));
extern_plonkWrite(load_at(25u, data2, 0u), load_at(26u, data2, 0u), load_at(27u, data2, 0u), load_at(28u, data2, 0u), load_at(29u, data2, 0u));
extern_plonkWrite(load_at(30u, data2, 0u), load_at(31u, data2, 0u), load_at(32u, data2, 0u), load_at(33u, data2, 0u), load_at(34u, data2, 0u));
extern_plonkWrite(load_at(35u, data2, 0u), load_at(36u, data2, 0u), load_at(37u, data2, 0u), load_at(38u, data2, 0u), load_at(39u, data2, 0u));
extern_plonkWrite(load_at(40u, data2, 0u), load_at(41u, data2, 0u), load_at(42u, data2, 0u), load_at(43u, data2, 0u), load_at(44u, data2, 0u));
extern_plonkWrite(load_at(45u, data2, 0u), load_at(46u, data2, 0u), load_at(47u, data2, 0u), load_at(48u, data2, 0u), load_at(49u, data2, 0u));
}
return 0u;
}
